// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

//go:build arm64

package ghostty

const abiAction_move_tab_sSize = uintptr(4)
const abiAction_move_tab_sAlign = uintptr(4)
const abiAction_move_tab_s_abiAmountOffset = uintptr(0)

const abiAction_search_selected_sSize = uintptr(4)
const abiAction_search_selected_sAlign = uintptr(4)
const abiAction_search_selected_s_abiSelectedOffset = uintptr(0)

const abiAction_search_total_sSize = uintptr(4)
const abiAction_search_total_sAlign = uintptr(4)
const abiAction_search_total_s_abiTotalOffset = uintptr(0)

const abiString_sSize = uintptr(16)
const abiString_sAlign = uintptr(8)
const abiString_s_abiPtrOffset = uintptr(0)
const abiString_s_abiLenOffset = uintptr(8)
const abiString_s_abiSentinelOffset = uintptr(12)
