// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

//go:build amd64

package ghostty

import (
	"testing"
	"unsafe"
)

func TestGeneratedABIAmd64(t *testing.T) {
	if got, want := unsafe.Sizeof(ActionMoveTabS{}), abiAction_move_tab_sSize; got != want {
		t.Errorf("ghostty_action_move_tab_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionMoveTabS{}), abiAction_move_tab_sAlign; got != want {
		t.Errorf("ghostty_action_move_tab_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionMoveTabS{}.Amount), abiAction_move_tab_s_abiAmountOffset; got != want {
		t.Errorf("ghostty_action_move_tab_s.amount offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSearchSelectedS{}), abiAction_search_selected_sSize; got != want {
		t.Errorf("ghostty_action_search_selected_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSearchSelectedS{}), abiAction_search_selected_sAlign; got != want {
		t.Errorf("ghostty_action_search_selected_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSearchSelectedS{}.Selected), abiAction_search_selected_s_abiSelectedOffset; got != want {
		t.Errorf("ghostty_action_search_selected_s.selected offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSearchTotalS{}), abiAction_search_total_sSize; got != want {
		t.Errorf("ghostty_action_search_total_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSearchTotalS{}), abiAction_search_total_sAlign; got != want {
		t.Errorf("ghostty_action_search_total_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSearchTotalS{}.Total), abiAction_search_total_s_abiTotalOffset; got != want {
		t.Errorf("ghostty_action_search_total_s.total offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(String{}), abiString_sSize; got != want {
		t.Errorf("ghostty_string_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(String{}), abiString_sAlign; got != want {
		t.Errorf("ghostty_string_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Ptr), abiString_s_abiPtrOffset; got != want {
		t.Errorf("ghostty_string_s.ptr offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Len), abiString_s_abiLenOffset; got != want {
		t.Errorf("ghostty_string_s.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Sentinel), abiString_s_abiSentinelOffset; got != want {
		t.Errorf("ghostty_string_s.sentinel offset = %d, want %d", got, want)
	}
}
