// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import (
	"testing"
	"unsafe"
)

func TestGeneratedABI(t *testing.T) {
	if got, want := unsafe.Sizeof(ActionCellSizeS{}), abiAction_cell_size_sSize; got != want {
		t.Errorf("ghostty_action_cell_size_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionCellSizeS{}), abiAction_cell_size_sAlign; got != want {
		t.Errorf("ghostty_action_cell_size_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionCellSizeS{}.Width), abiAction_cell_size_s_abiWidthOffset; got != want {
		t.Errorf("ghostty_action_cell_size_s.width offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionCellSizeS{}.Height), abiAction_cell_size_s_abiHeightOffset; got != want {
		t.Errorf("ghostty_action_cell_size_s.height offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionColorChangeS{}), abiAction_color_change_sSize; got != want {
		t.Errorf("ghostty_action_color_change_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionColorChangeS{}), abiAction_color_change_sAlign; got != want {
		t.Errorf("ghostty_action_color_change_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionColorChangeS{}.Kind), abiAction_color_change_s_abiKindOffset; got != want {
		t.Errorf("ghostty_action_color_change_s.kind offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionColorChangeS{}.R), abiAction_color_change_s_abiROffset; got != want {
		t.Errorf("ghostty_action_color_change_s.r offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionColorChangeS{}.G), abiAction_color_change_s_abiGOffset; got != want {
		t.Errorf("ghostty_action_color_change_s.g offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionColorChangeS{}.B), abiAction_color_change_s_abiBOffset; got != want {
		t.Errorf("ghostty_action_color_change_s.b offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionCommandFinishedS{}), abiAction_command_finished_sSize; got != want {
		t.Errorf("ghostty_action_command_finished_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionCommandFinishedS{}), abiAction_command_finished_sAlign; got != want {
		t.Errorf("ghostty_action_command_finished_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionCommandFinishedS{}.ExitCode), abiAction_command_finished_s_abiExit_codeOffset; got != want {
		t.Errorf("ghostty_action_command_finished_s.exit_code offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionCommandFinishedS{}.Duration), abiAction_command_finished_s_abiDurationOffset; got != want {
		t.Errorf("ghostty_action_command_finished_s.duration offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionConfigChangeS{}), abiAction_config_change_sSize; got != want {
		t.Errorf("ghostty_action_config_change_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionConfigChangeS{}), abiAction_config_change_sAlign; got != want {
		t.Errorf("ghostty_action_config_change_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionConfigChangeS{}.Config), abiAction_config_change_s_abiConfigOffset; got != want {
		t.Errorf("ghostty_action_config_change_s.config offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionDesktopNotificationS{}), abiAction_desktop_notification_sSize; got != want {
		t.Errorf("ghostty_action_desktop_notification_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionDesktopNotificationS{}), abiAction_desktop_notification_sAlign; got != want {
		t.Errorf("ghostty_action_desktop_notification_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionDesktopNotificationS{}.Title), abiAction_desktop_notification_s_abiTitleOffset; got != want {
		t.Errorf("ghostty_action_desktop_notification_s.title offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionDesktopNotificationS{}.Body), abiAction_desktop_notification_s_abiBodyOffset; got != want {
		t.Errorf("ghostty_action_desktop_notification_s.body offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionInitialSizeS{}), abiAction_initial_size_sSize; got != want {
		t.Errorf("ghostty_action_initial_size_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionInitialSizeS{}), abiAction_initial_size_sAlign; got != want {
		t.Errorf("ghostty_action_initial_size_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionInitialSizeS{}.Width), abiAction_initial_size_s_abiWidthOffset; got != want {
		t.Errorf("ghostty_action_initial_size_s.width offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionInitialSizeS{}.Height), abiAction_initial_size_s_abiHeightOffset; got != want {
		t.Errorf("ghostty_action_initial_size_s.height offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionKeySequenceS{}), abiAction_key_sequence_sSize; got != want {
		t.Errorf("ghostty_action_key_sequence_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionKeySequenceS{}), abiAction_key_sequence_sAlign; got != want {
		t.Errorf("ghostty_action_key_sequence_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeySequenceS{}.Active), abiAction_key_sequence_s_abiActiveOffset; got != want {
		t.Errorf("ghostty_action_key_sequence_s.active offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeySequenceS{}.Trigger), abiAction_key_sequence_s_abiTriggerOffset; got != want {
		t.Errorf("ghostty_action_key_sequence_s.trigger offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionKeyTableS{}), abiAction_key_table_sSize; got != want {
		t.Errorf("ghostty_action_key_table_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionKeyTableS{}), abiAction_key_table_sAlign; got != want {
		t.Errorf("ghostty_action_key_table_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeyTableS{}.Tag), abiAction_key_table_s_abiTagOffset; got != want {
		t.Errorf("ghostty_action_key_table_s.tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeyTableS{}.Value), abiAction_key_table_s_abiValueOffset; got != want {
		t.Errorf("ghostty_action_key_table_s.value offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionKeyTableU{}), abiAction_key_table_uSize; got != want {
		t.Errorf("ghostty_action_key_table_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionKeyTableU{}), abiAction_key_table_uAlign; got != want {
		t.Errorf("ghostty_action_key_table_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionKeyTableActivate{}), abiAction_key_table_u_activateSize; got != want {
		t.Errorf("ghostty_action_key_table_u.activate size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionKeyTableActivate{}), abiAction_key_table_u_activateAlign; got != want {
		t.Errorf("ghostty_action_key_table_u.activate align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeyTableActivate{}.Name), abiAction_key_table_u_activate_abiNameOffset; got != want {
		t.Errorf("ghostty_action_key_table_u.activate.name offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionKeyTableActivate{}.Len), abiAction_key_table_u_activate_abiLenOffset; got != want {
		t.Errorf("ghostty_action_key_table_u.activate.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionMouseOverLinkS{}), abiAction_mouse_over_link_sSize; got != want {
		t.Errorf("ghostty_action_mouse_over_link_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionMouseOverLinkS{}), abiAction_mouse_over_link_sAlign; got != want {
		t.Errorf("ghostty_action_mouse_over_link_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionMouseOverLinkS{}.URL), abiAction_mouse_over_link_s_abiUrlOffset; got != want {
		t.Errorf("ghostty_action_mouse_over_link_s.url offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionMouseOverLinkS{}.Len), abiAction_mouse_over_link_s_abiLenOffset; got != want {
		t.Errorf("ghostty_action_mouse_over_link_s.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionMoveTabS{}), abiAction_move_tab_sSize; got != want {
		t.Errorf("ghostty_action_move_tab_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionMoveTabS{}), abiAction_move_tab_sAlign; got != want {
		t.Errorf("ghostty_action_move_tab_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionMoveTabS{}.Amount), abiAction_move_tab_s_abiAmountOffset; got != want {
		t.Errorf("ghostty_action_move_tab_s.amount offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionOpenURLS{}), abiAction_open_url_sSize; got != want {
		t.Errorf("ghostty_action_open_url_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionOpenURLS{}), abiAction_open_url_sAlign; got != want {
		t.Errorf("ghostty_action_open_url_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionOpenURLS{}.Kind), abiAction_open_url_s_abiKindOffset; got != want {
		t.Errorf("ghostty_action_open_url_s.kind offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionOpenURLS{}.URL), abiAction_open_url_s_abiUrlOffset; got != want {
		t.Errorf("ghostty_action_open_url_s.url offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionOpenURLS{}.Len), abiAction_open_url_s_abiLenOffset; got != want {
		t.Errorf("ghostty_action_open_url_s.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionProgressReportS{}), abiAction_progress_report_sSize; got != want {
		t.Errorf("ghostty_action_progress_report_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionProgressReportS{}), abiAction_progress_report_sAlign; got != want {
		t.Errorf("ghostty_action_progress_report_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionProgressReportS{}.State), abiAction_progress_report_s_abiStateOffset; got != want {
		t.Errorf("ghostty_action_progress_report_s.state offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionProgressReportS{}.Progress), abiAction_progress_report_s_abiProgressOffset; got != want {
		t.Errorf("ghostty_action_progress_report_s.progress offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionPwdS{}), abiAction_pwd_sSize; got != want {
		t.Errorf("ghostty_action_pwd_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionPwdS{}), abiAction_pwd_sAlign; got != want {
		t.Errorf("ghostty_action_pwd_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionPwdS{}.Pwd), abiAction_pwd_s_abiPwdOffset; got != want {
		t.Errorf("ghostty_action_pwd_s.pwd offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionReloadConfigS{}), abiAction_reload_config_sSize; got != want {
		t.Errorf("ghostty_action_reload_config_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionReloadConfigS{}), abiAction_reload_config_sAlign; got != want {
		t.Errorf("ghostty_action_reload_config_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionReloadConfigS{}.Soft), abiAction_reload_config_s_abiSoftOffset; got != want {
		t.Errorf("ghostty_action_reload_config_s.soft offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionResizeSplitS{}), abiAction_resize_split_sSize; got != want {
		t.Errorf("ghostty_action_resize_split_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionResizeSplitS{}), abiAction_resize_split_sAlign; got != want {
		t.Errorf("ghostty_action_resize_split_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionResizeSplitS{}.Amount), abiAction_resize_split_s_abiAmountOffset; got != want {
		t.Errorf("ghostty_action_resize_split_s.amount offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionResizeSplitS{}.Direction), abiAction_resize_split_s_abiDirectionOffset; got != want {
		t.Errorf("ghostty_action_resize_split_s.direction offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionS{}), abiAction_sSize; got != want {
		t.Errorf("ghostty_action_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionS{}), abiAction_sAlign; got != want {
		t.Errorf("ghostty_action_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionS{}.Tag), abiAction_s_abiTagOffset; got != want {
		t.Errorf("ghostty_action_s.tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionS{}.Action), abiAction_s_abiActionOffset; got != want {
		t.Errorf("ghostty_action_s.action offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionScrollbarS{}), abiAction_scrollbar_sSize; got != want {
		t.Errorf("ghostty_action_scrollbar_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionScrollbarS{}), abiAction_scrollbar_sAlign; got != want {
		t.Errorf("ghostty_action_scrollbar_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionScrollbarS{}.Total), abiAction_scrollbar_s_abiTotalOffset; got != want {
		t.Errorf("ghostty_action_scrollbar_s.total offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionScrollbarS{}.Offset), abiAction_scrollbar_s_abiOffsetOffset; got != want {
		t.Errorf("ghostty_action_scrollbar_s.offset offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionScrollbarS{}.Len), abiAction_scrollbar_s_abiLenOffset; got != want {
		t.Errorf("ghostty_action_scrollbar_s.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSearchSelectedS{}), abiAction_search_selected_sSize; got != want {
		t.Errorf("ghostty_action_search_selected_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSearchSelectedS{}), abiAction_search_selected_sAlign; got != want {
		t.Errorf("ghostty_action_search_selected_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSearchSelectedS{}.Selected), abiAction_search_selected_s_abiSelectedOffset; got != want {
		t.Errorf("ghostty_action_search_selected_s.selected offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSearchTotalS{}), abiAction_search_total_sSize; got != want {
		t.Errorf("ghostty_action_search_total_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSearchTotalS{}), abiAction_search_total_sAlign; got != want {
		t.Errorf("ghostty_action_search_total_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSearchTotalS{}.Total), abiAction_search_total_s_abiTotalOffset; got != want {
		t.Errorf("ghostty_action_search_total_s.total offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSetTitleS{}), abiAction_set_title_sSize; got != want {
		t.Errorf("ghostty_action_set_title_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSetTitleS{}), abiAction_set_title_sAlign; got != want {
		t.Errorf("ghostty_action_set_title_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSetTitleS{}.Title), abiAction_set_title_s_abiTitleOffset; got != want {
		t.Errorf("ghostty_action_set_title_s.title offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionSizeLimitS{}), abiAction_size_limit_sSize; got != want {
		t.Errorf("ghostty_action_size_limit_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionSizeLimitS{}), abiAction_size_limit_sAlign; got != want {
		t.Errorf("ghostty_action_size_limit_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSizeLimitS{}.MinWidth), abiAction_size_limit_s_abiMin_widthOffset; got != want {
		t.Errorf("ghostty_action_size_limit_s.min_width offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSizeLimitS{}.MinHeight), abiAction_size_limit_s_abiMin_heightOffset; got != want {
		t.Errorf("ghostty_action_size_limit_s.min_height offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSizeLimitS{}.MaxWidth), abiAction_size_limit_s_abiMax_widthOffset; got != want {
		t.Errorf("ghostty_action_size_limit_s.max_width offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionSizeLimitS{}.MaxHeight), abiAction_size_limit_s_abiMax_heightOffset; got != want {
		t.Errorf("ghostty_action_size_limit_s.max_height offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionStartSearchS{}), abiAction_start_search_sSize; got != want {
		t.Errorf("ghostty_action_start_search_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionStartSearchS{}), abiAction_start_search_sAlign; got != want {
		t.Errorf("ghostty_action_start_search_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ActionStartSearchS{}.Needle), abiAction_start_search_s_abiNeedleOffset; got != want {
		t.Errorf("ghostty_action_start_search_s.needle offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ActionU{}), abiAction_uSize; got != want {
		t.Errorf("ghostty_action_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ActionU{}), abiAction_uAlign; got != want {
		t.Errorf("ghostty_action_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(ClipboardContent{}), abiClipboard_content_sSize; got != want {
		t.Errorf("ghostty_clipboard_content_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(ClipboardContent{}), abiClipboard_content_sAlign; got != want {
		t.Errorf("ghostty_clipboard_content_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ClipboardContent{}.Mime), abiClipboard_content_s_abiMimeOffset; got != want {
		t.Errorf("ghostty_clipboard_content_s.mime offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(ClipboardContent{}.Data), abiClipboard_content_s_abiDataOffset; got != want {
		t.Errorf("ghostty_clipboard_content_s.data offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(Diagnostic{}), abiDiagnostic_sSize; got != want {
		t.Errorf("ghostty_diagnostic_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(Diagnostic{}), abiDiagnostic_sAlign; got != want {
		t.Errorf("ghostty_diagnostic_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Diagnostic{}.Message), abiDiagnostic_s_abiMessageOffset; got != want {
		t.Errorf("ghostty_diagnostic_s.message offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(EnvVar{}), abiEnv_var_sSize; got != want {
		t.Errorf("ghostty_env_var_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(EnvVar{}), abiEnv_var_sAlign; got != want {
		t.Errorf("ghostty_env_var_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(EnvVar{}.Key), abiEnv_var_s_abiKeyOffset; got != want {
		t.Errorf("ghostty_env_var_s.key offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(EnvVar{}.Value), abiEnv_var_s_abiValueOffset; got != want {
		t.Errorf("ghostty_env_var_s.value offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(InfoS{}), abiInfo_sSize; got != want {
		t.Errorf("ghostty_info_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(InfoS{}), abiInfo_sAlign; got != want {
		t.Errorf("ghostty_info_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InfoS{}.BuildMode), abiInfo_s_abiBuild_modeOffset; got != want {
		t.Errorf("ghostty_info_s.build_mode offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InfoS{}.Version), abiInfo_s_abiVersionOffset; got != want {
		t.Errorf("ghostty_info_s.version offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InfoS{}.VersionLen), abiInfo_s_abiVersion_lenOffset; got != want {
		t.Errorf("ghostty_info_s.version_len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(InputKeyS{}), abiInput_key_sSize; got != want {
		t.Errorf("ghostty_input_key_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(InputKeyS{}), abiInput_key_sAlign; got != want {
		t.Errorf("ghostty_input_key_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.Action), abiInput_key_s_abiActionOffset; got != want {
		t.Errorf("ghostty_input_key_s.action offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.Mods), abiInput_key_s_abiModsOffset; got != want {
		t.Errorf("ghostty_input_key_s.mods offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.ConsumedMods), abiInput_key_s_abiConsumed_modsOffset; got != want {
		t.Errorf("ghostty_input_key_s.consumed_mods offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.Keycode), abiInput_key_s_abiKeycodeOffset; got != want {
		t.Errorf("ghostty_input_key_s.keycode offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.Text), abiInput_key_s_abiTextOffset; got != want {
		t.Errorf("ghostty_input_key_s.text offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.UnshiftedCodepoint), abiInput_key_s_abiUnshifted_codepointOffset; got != want {
		t.Errorf("ghostty_input_key_s.unshifted_codepoint offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputKeyS{}.Composing), abiInput_key_s_abiComposingOffset; got != want {
		t.Errorf("ghostty_input_key_s.composing offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(InputTriggerKey{}), abiInput_trigger_key_uSize; got != want {
		t.Errorf("ghostty_input_trigger_key_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(InputTriggerKey{}), abiInput_trigger_key_uAlign; got != want {
		t.Errorf("ghostty_input_trigger_key_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(InputTrigger{}), abiInput_trigger_sSize; got != want {
		t.Errorf("ghostty_input_trigger_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(InputTrigger{}), abiInput_trigger_sAlign; got != want {
		t.Errorf("ghostty_input_trigger_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputTrigger{}.Tag), abiInput_trigger_s_abiTagOffset; got != want {
		t.Errorf("ghostty_input_trigger_s.tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputTrigger{}.Key), abiInput_trigger_s_abiKeyOffset; got != want {
		t.Errorf("ghostty_input_trigger_s.key offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(InputTrigger{}.Mods), abiInput_trigger_s_abiModsOffset; got != want {
		t.Errorf("ghostty_input_trigger_s.mods offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(IPCActionNewWindow{}), abiIpc_action_new_window_sSize; got != want {
		t.Errorf("ghostty_ipc_action_new_window_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(IPCActionNewWindow{}), abiIpc_action_new_window_sAlign; got != want {
		t.Errorf("ghostty_ipc_action_new_window_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(IPCActionNewWindow{}.Arguments), abiIpc_action_new_window_s_abiArgumentsOffset; got != want {
		t.Errorf("ghostty_ipc_action_new_window_s.arguments offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(IPCAction{}), abiIpc_action_uSize; got != want {
		t.Errorf("ghostty_ipc_action_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(IPCAction{}), abiIpc_action_uAlign; got != want {
		t.Errorf("ghostty_ipc_action_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(IPCTarget{}), abiIpc_target_uSize; got != want {
		t.Errorf("ghostty_ipc_target_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(IPCTarget{}), abiIpc_target_uAlign; got != want {
		t.Errorf("ghostty_ipc_target_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(PlatformIosS{}), abiPlatform_ios_sSize; got != want {
		t.Errorf("ghostty_platform_ios_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(PlatformIosS{}), abiPlatform_ios_sAlign; got != want {
		t.Errorf("ghostty_platform_ios_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(PlatformIosS{}.Uiview), abiPlatform_ios_s_abiUiviewOffset; got != want {
		t.Errorf("ghostty_platform_ios_s.uiview offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(PlatformMacosS{}), abiPlatform_macos_sSize; got != want {
		t.Errorf("ghostty_platform_macos_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(PlatformMacosS{}), abiPlatform_macos_sAlign; got != want {
		t.Errorf("ghostty_platform_macos_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(PlatformMacosS{}.Nsview), abiPlatform_macos_s_abiNsviewOffset; got != want {
		t.Errorf("ghostty_platform_macos_s.nsview offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(PlatformU{}), abiPlatform_uSize; got != want {
		t.Errorf("ghostty_platform_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(PlatformU{}), abiPlatform_uAlign; got != want {
		t.Errorf("ghostty_platform_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(Point{}), abiPoint_sSize; got != want {
		t.Errorf("ghostty_point_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(Point{}), abiPoint_sAlign; got != want {
		t.Errorf("ghostty_point_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Point{}.Tag), abiPoint_s_abiTagOffset; got != want {
		t.Errorf("ghostty_point_s.tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Point{}.Coord), abiPoint_s_abiCoordOffset; got != want {
		t.Errorf("ghostty_point_s.coord offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Point{}.X), abiPoint_s_abiXOffset; got != want {
		t.Errorf("ghostty_point_s.x offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Point{}.Y), abiPoint_s_abiYOffset; got != want {
		t.Errorf("ghostty_point_s.y offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(QuickTerminalSizeValue{}), abiQuick_terminal_size_value_uSize; got != want {
		t.Errorf("ghostty_quick_terminal_size_value_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(QuickTerminalSizeValue{}), abiQuick_terminal_size_value_uAlign; got != want {
		t.Errorf("ghostty_quick_terminal_size_value_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(RuntimeConfig{}), abiRuntime_config_sSize; got != want {
		t.Errorf("ghostty_runtime_config_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(RuntimeConfig{}), abiRuntime_config_sAlign; got != want {
		t.Errorf("ghostty_runtime_config_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.Userdata), abiRuntime_config_s_abiUserdataOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.userdata offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.SupportsSelectionClipboard), abiRuntime_config_s_abiSupports_selection_clipboardOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.supports_selection_clipboard offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.WakeupCb), abiRuntime_config_s_abiWakeup_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.wakeup_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.ActionCb), abiRuntime_config_s_abiAction_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.action_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.ReadClipboardCb), abiRuntime_config_s_abiRead_clipboard_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.read_clipboard_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.ConfirmReadClipboardCb), abiRuntime_config_s_abiConfirm_read_clipboard_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.confirm_read_clipboard_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.WriteClipboardCb), abiRuntime_config_s_abiWrite_clipboard_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.write_clipboard_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(RuntimeConfig{}.CloseSurfaceCb), abiRuntime_config_s_abiClose_surface_cbOffset; got != want {
		t.Errorf("ghostty_runtime_config_s.close_surface_cb offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(Selection{}), abiSelection_sSize; got != want {
		t.Errorf("ghostty_selection_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(Selection{}), abiSelection_sAlign; got != want {
		t.Errorf("ghostty_selection_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Selection{}.TopLeft), abiSelection_s_abiTop_leftOffset; got != want {
		t.Errorf("ghostty_selection_s.top_left offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Selection{}.BottomRight), abiSelection_s_abiBottom_rightOffset; got != want {
		t.Errorf("ghostty_selection_s.bottom_right offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Selection{}.Rectangle), abiSelection_s_abiRectangleOffset; got != want {
		t.Errorf("ghostty_selection_s.rectangle offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(String{}), abiString_sSize; got != want {
		t.Errorf("ghostty_string_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(String{}), abiString_sAlign; got != want {
		t.Errorf("ghostty_string_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Ptr), abiString_s_abiPtrOffset; got != want {
		t.Errorf("ghostty_string_s.ptr offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Len), abiString_s_abiLenOffset; got != want {
		t.Errorf("ghostty_string_s.len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(String{}.Sentinel), abiString_s_abiSentinelOffset; got != want {
		t.Errorf("ghostty_string_s.sentinel offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(SurfaceConfig{}), abiSurface_config_sSize; got != want {
		t.Errorf("ghostty_surface_config_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(SurfaceConfig{}), abiSurface_config_sAlign; got != want {
		t.Errorf("ghostty_surface_config_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.PlatformTag), abiSurface_config_s_abiPlatform_tagOffset; got != want {
		t.Errorf("ghostty_surface_config_s.platform_tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.Platform), abiSurface_config_s_abiPlatformOffset; got != want {
		t.Errorf("ghostty_surface_config_s.platform offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.Userdata), abiSurface_config_s_abiUserdataOffset; got != want {
		t.Errorf("ghostty_surface_config_s.userdata offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.ScaleFactor), abiSurface_config_s_abiScale_factorOffset; got != want {
		t.Errorf("ghostty_surface_config_s.scale_factor offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.FontSize), abiSurface_config_s_abiFont_sizeOffset; got != want {
		t.Errorf("ghostty_surface_config_s.font_size offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.WorkingDirectory), abiSurface_config_s_abiWorking_directoryOffset; got != want {
		t.Errorf("ghostty_surface_config_s.working_directory offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.Command), abiSurface_config_s_abiCommandOffset; got != want {
		t.Errorf("ghostty_surface_config_s.command offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.EnvVars), abiSurface_config_s_abiEnv_varsOffset; got != want {
		t.Errorf("ghostty_surface_config_s.env_vars offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.EnvVarCount), abiSurface_config_s_abiEnv_var_countOffset; got != want {
		t.Errorf("ghostty_surface_config_s.env_var_count offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.InitialInput), abiSurface_config_s_abiInitial_inputOffset; got != want {
		t.Errorf("ghostty_surface_config_s.initial_input offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.WaitAfterCommand), abiSurface_config_s_abiWait_after_commandOffset; got != want {
		t.Errorf("ghostty_surface_config_s.wait_after_command offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceConfig{}.Context), abiSurface_config_s_abiContextOffset; got != want {
		t.Errorf("ghostty_surface_config_s.context offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(SurfaceMessageChildexited{}), abiSurface_message_childexited_sSize; got != want {
		t.Errorf("ghostty_surface_message_childexited_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(SurfaceMessageChildexited{}), abiSurface_message_childexited_sAlign; got != want {
		t.Errorf("ghostty_surface_message_childexited_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceMessageChildexited{}.ExitCode), abiSurface_message_childexited_s_abiExit_codeOffset; got != want {
		t.Errorf("ghostty_surface_message_childexited_s.exit_code offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceMessageChildexited{}.TimetimeMs), abiSurface_message_childexited_s_abiTimetime_msOffset; got != want {
		t.Errorf("ghostty_surface_message_childexited_s.timetime_ms offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(SurfaceSizeS{}), abiSurface_size_sSize; got != want {
		t.Errorf("ghostty_surface_size_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(SurfaceSizeS{}), abiSurface_size_sAlign; got != want {
		t.Errorf("ghostty_surface_size_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.Columns), abiSurface_size_s_abiColumnsOffset; got != want {
		t.Errorf("ghostty_surface_size_s.columns offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.Rows), abiSurface_size_s_abiRowsOffset; got != want {
		t.Errorf("ghostty_surface_size_s.rows offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.WidthPx), abiSurface_size_s_abiWidth_pxOffset; got != want {
		t.Errorf("ghostty_surface_size_s.width_px offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.HeightPx), abiSurface_size_s_abiHeight_pxOffset; got != want {
		t.Errorf("ghostty_surface_size_s.height_px offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.CellWidthPx), abiSurface_size_s_abiCell_width_pxOffset; got != want {
		t.Errorf("ghostty_surface_size_s.cell_width_px offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(SurfaceSizeS{}.CellHeightPx), abiSurface_size_s_abiCell_height_pxOffset; got != want {
		t.Errorf("ghostty_surface_size_s.cell_height_px offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(TargetS{}), abiTarget_sSize; got != want {
		t.Errorf("ghostty_target_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(TargetS{}), abiTarget_sAlign; got != want {
		t.Errorf("ghostty_target_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(TargetS{}.Tag), abiTarget_s_abiTagOffset; got != want {
		t.Errorf("ghostty_target_s.tag offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(TargetS{}.Target), abiTarget_s_abiTargetOffset; got != want {
		t.Errorf("ghostty_target_s.target offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(TargetU{}), abiTarget_uSize; got != want {
		t.Errorf("ghostty_target_u size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(TargetU{}), abiTarget_uAlign; got != want {
		t.Errorf("ghostty_target_u align = %d, want %d", got, want)
	}
	if got, want := unsafe.Sizeof(Text{}), abiText_sSize; got != want {
		t.Errorf("ghostty_text_s size = %d, want %d", got, want)
	}
	if got, want := unsafe.Alignof(Text{}), abiText_sAlign; got != want {
		t.Errorf("ghostty_text_s align = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.TlPxX), abiText_s_abiTl_px_xOffset; got != want {
		t.Errorf("ghostty_text_s.tl_px_x offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.TlPxY), abiText_s_abiTl_px_yOffset; got != want {
		t.Errorf("ghostty_text_s.tl_px_y offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.OffsetStart), abiText_s_abiOffset_startOffset; got != want {
		t.Errorf("ghostty_text_s.offset_start offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.OffsetLen), abiText_s_abiOffset_lenOffset; got != want {
		t.Errorf("ghostty_text_s.offset_len offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.Text), abiText_s_abiTextOffset; got != want {
		t.Errorf("ghostty_text_s.text offset = %d, want %d", got, want)
	}
	if got, want := unsafe.Offsetof(Text{}.TextLen), abiText_s_abiText_lenOffset; got != want {
		t.Errorf("ghostty_text_s.text_len offset = %d, want %d", got, want)
	}
}
