// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

const (
	ActionCloseTabModeThis  ActionCloseTabMode = 0
	ActionCloseTabModeOther ActionCloseTabMode = 1
	ActionCloseTabModeRight ActionCloseTabMode = 2
)

const (
	ActionColorKindForeground ActionColorKind = -1
	ActionColorKindBackground ActionColorKind = -2
	ActionColorKindCursor     ActionColorKind = -3
)

const (
	FloatWindowOn     ActionFloatWindowE = 0
	FloatWindowOff    ActionFloatWindowE = 1
	FloatWindowToggle ActionFloatWindowE = 2
)

const (
	FullscreenNative                    ActionFullscreen = 0
	FullscreenMacosNonNative            ActionFullscreen = 1
	FullscreenMacosNonNativeVisibleMenu ActionFullscreen = 2
	FullscreenMacosNonNativePaddedNotch ActionFullscreen = 3
)

const (
	GotoSplitPrevious ActionGotoSplitE = 0
	GotoSplitNext     ActionGotoSplitE = 1
	GotoSplitUp       ActionGotoSplitE = 2
	GotoSplitLeft     ActionGotoSplitE = 3
	GotoSplitDown     ActionGotoSplitE = 4
	GotoSplitRight    ActionGotoSplitE = 5
)

const (
	GotoTabPrevious ActionGotoTabE = -1
	GotoTabNext     ActionGotoTabE = -2
	GotoTabLast     ActionGotoTabE = -3
)

const (
	GotoWindowPrevious ActionGotoWindowE = 0
	GotoWindowNext     ActionGotoWindowE = 1
)

const (
	InspectorToggle ActionInspectorE = 0
	InspectorShow   ActionInspectorE = 1
	InspectorHide   ActionInspectorE = 2
)

const (
	KeyTableActivate      ActionKeyTableTag = 0
	KeyTableDeactivate    ActionKeyTableTag = 1
	KeyTableDeactivateAll ActionKeyTableTag = 2
)

const (
	MouseShapeDefault      ActionMouseShapeE = 0
	MouseShapeContextMenu  ActionMouseShapeE = 1
	MouseShapeHelp         ActionMouseShapeE = 2
	MouseShapePointer      ActionMouseShapeE = 3
	MouseShapeProgress     ActionMouseShapeE = 4
	MouseShapeWait         ActionMouseShapeE = 5
	MouseShapeCell         ActionMouseShapeE = 6
	MouseShapeCrosshair    ActionMouseShapeE = 7
	MouseShapeText         ActionMouseShapeE = 8
	MouseShapeVerticalText ActionMouseShapeE = 9
	MouseShapeAlias        ActionMouseShapeE = 10
	MouseShapeCopy         ActionMouseShapeE = 11
	MouseShapeMove         ActionMouseShapeE = 12
	MouseShapeNoDrop       ActionMouseShapeE = 13
	MouseShapeNotAllowed   ActionMouseShapeE = 14
	MouseShapeGrab         ActionMouseShapeE = 15
	MouseShapeGrabbing     ActionMouseShapeE = 16
	MouseShapeAllScroll    ActionMouseShapeE = 17
	MouseShapeColResize    ActionMouseShapeE = 18
	MouseShapeRowResize    ActionMouseShapeE = 19
	MouseShapeNResize      ActionMouseShapeE = 20
	MouseShapeEResize      ActionMouseShapeE = 21
	MouseShapeSResize      ActionMouseShapeE = 22
	MouseShapeWResize      ActionMouseShapeE = 23
	MouseShapeNeResize     ActionMouseShapeE = 24
	MouseShapeNwResize     ActionMouseShapeE = 25
	MouseShapeSeResize     ActionMouseShapeE = 26
	MouseShapeSwResize     ActionMouseShapeE = 27
	MouseShapeEwResize     ActionMouseShapeE = 28
	MouseShapeNsResize     ActionMouseShapeE = 29
	MouseShapeNeswResize   ActionMouseShapeE = 30
	MouseShapeNwseResize   ActionMouseShapeE = 31
	MouseShapeZoomIn       ActionMouseShapeE = 32
	MouseShapeZoomOut      ActionMouseShapeE = 33
)

const (
	MouseVisible ActionMouseVisibilityE = 0
	MouseHidden  ActionMouseVisibilityE = 1
)

const (
	ActionOpenURLKindUnknown ActionOpenURLKind = 0
	ActionOpenURLKindText    ActionOpenURLKind = 1
	ActionOpenURLKindHtml    ActionOpenURLKind = 2
)

const (
	ProgressStateRemove        ActionProgressReportState = 0
	ProgressStateSet           ActionProgressReportState = 1
	ProgressStateError         ActionProgressReportState = 2
	ProgressStateIndeterminate ActionProgressReportState = 3
	ProgressStatePause         ActionProgressReportState = 4
)

const (
	PromptTitleSurface ActionPromptTitleE = 0
	PromptTitleTab     ActionPromptTitleE = 1
)

const (
	QuitTimerStart ActionQuitTimerE = 0
	QuitTimerStop  ActionQuitTimerE = 1
)

const (
	ReadonlyOff ActionReadonlyE = 0
	ReadonlyOn  ActionReadonlyE = 1
)

const (
	RendererHealthHealthy   ActionRendererHealthE = 0
	RendererHealthUnhealthy ActionRendererHealthE = 1
)

const (
	ResizeSplitUp    ActionResizeSplitDirection = 0
	ResizeSplitDown  ActionResizeSplitDirection = 1
	ResizeSplitLeft  ActionResizeSplitDirection = 2
	ResizeSplitRight ActionResizeSplitDirection = 3
)

const (
	SecureInputOn     ActionSecureInputE = 0
	SecureInputOff    ActionSecureInputE = 1
	SecureInputToggle ActionSecureInputE = 2
)

const (
	SplitDirectionRight ActionSplitDirection = 0
	SplitDirectionDown  ActionSplitDirection = 1
	SplitDirectionLeft  ActionSplitDirection = 2
	SplitDirectionUp    ActionSplitDirection = 3
)

const (
	ActionQuit                    ActionTag = 0
	ActionNewWindow               ActionTag = 1
	ActionNewTab                  ActionTag = 2
	ActionCloseTab                ActionTag = 3
	ActionNewSplit                ActionTag = 4
	ActionCloseAllWindows         ActionTag = 5
	ActionToggleMaximize          ActionTag = 6
	ActionToggleFullscreen        ActionTag = 7
	ActionToggleTabOverview       ActionTag = 8
	ActionToggleWindowDecorations ActionTag = 9
	ActionToggleQuickTerminal     ActionTag = 10
	ActionToggleCommandPalette    ActionTag = 11
	ActionToggleVisibility        ActionTag = 12
	ActionToggleBackgroundOpacity ActionTag = 13
	ActionMoveTab                 ActionTag = 14
	ActionGotoTab                 ActionTag = 15
	ActionGotoSplit               ActionTag = 16
	ActionGotoWindow              ActionTag = 17
	ActionResizeSplit             ActionTag = 18
	ActionEqualizeSplits          ActionTag = 19
	ActionToggleSplitZoom         ActionTag = 20
	ActionPresentTerminal         ActionTag = 21
	ActionSizeLimit               ActionTag = 22
	ActionResetWindowSize         ActionTag = 23
	ActionInitialSize             ActionTag = 24
	ActionCellSize                ActionTag = 25
	ActionScrollbar               ActionTag = 26
	ActionRender                  ActionTag = 27
	ActionInspector               ActionTag = 28
	ActionShowGtkInspector        ActionTag = 29
	ActionRenderInspector         ActionTag = 30
	ActionDesktopNotification     ActionTag = 31
	ActionSetTitle                ActionTag = 32
	ActionSetTabTitle             ActionTag = 33
	ActionPromptTitle             ActionTag = 34
	ActionPwd                     ActionTag = 35
	ActionMouseShape              ActionTag = 36
	ActionMouseVisibility         ActionTag = 37
	ActionMouseOverLink           ActionTag = 38
	ActionRendererHealth          ActionTag = 39
	ActionOpenConfig              ActionTag = 40
	ActionQuitTimer               ActionTag = 41
	ActionFloatWindow             ActionTag = 42
	ActionSecureInput             ActionTag = 43
	ActionKeySequence             ActionTag = 44
	ActionKeyTable                ActionTag = 45
	ActionColorChange             ActionTag = 46
	ActionReloadConfig            ActionTag = 47
	ActionConfigChange            ActionTag = 48
	ActionCloseWindow             ActionTag = 49
	ActionRingBell                ActionTag = 50
	ActionSelectionChanged        ActionTag = 51
	ActionUndo                    ActionTag = 52
	ActionRedo                    ActionTag = 53
	ActionCheckForUpdates         ActionTag = 54
	ActionOpenURL                 ActionTag = 55
	ActionShowChildExited         ActionTag = 56
	ActionProgressReport          ActionTag = 57
	ActionShowOnScreenKeyboard    ActionTag = 58
	ActionCommandFinished         ActionTag = 59
	ActionStartSearch             ActionTag = 60
	ActionEndSearch               ActionTag = 61
	ActionSearchTotal             ActionTag = 62
	ActionSearchSelected          ActionTag = 63
	ActionReadonly                ActionTag = 64
	ActionCopyTitleToClipboard    ActionTag = 65
)

const (
	BindingFlagsConsumed    BindingFlags = 1
	BindingFlagsAll         BindingFlags = 2
	BindingFlagsGlobal      BindingFlags = 4
	BindingFlagsPerformable BindingFlags = 8
)

const (
	BuildModeDebug        BuildMode = 0
	BuildModeReleaseSafe  BuildMode = 1
	BuildModeReleaseFast  BuildMode = 2
	BuildModeReleaseSmall BuildMode = 3
)

const (
	ClipboardStandard  Clipboard = 0
	ClipboardSelection Clipboard = 1
)

const (
	ClipboardRequestPaste      ClipboardRequest = 0
	ClipboardRequestOsc52Read  ClipboardRequest = 1
	ClipboardRequestOsc52Write ClipboardRequest = 2
)

const (
	ColorSchemeLight ColorScheme = 0
	ColorSchemeDark  ColorScheme = 1
)

const (
	ActionRelease InputAction = 0
	ActionPress   InputAction = 1
	ActionRepeat  InputAction = 2
)

const (
	KeyUnidentified         InputKeyE = 0
	KeyBackquote            InputKeyE = 1
	KeyBackslash            InputKeyE = 2
	KeyBracketLeft          InputKeyE = 3
	KeyBracketRight         InputKeyE = 4
	KeyComma                InputKeyE = 5
	KeyDigit0               InputKeyE = 6
	KeyDigit1               InputKeyE = 7
	KeyDigit2               InputKeyE = 8
	KeyDigit3               InputKeyE = 9
	KeyDigit4               InputKeyE = 10
	KeyDigit5               InputKeyE = 11
	KeyDigit6               InputKeyE = 12
	KeyDigit7               InputKeyE = 13
	KeyDigit8               InputKeyE = 14
	KeyDigit9               InputKeyE = 15
	KeyEqual                InputKeyE = 16
	KeyIntlBackslash        InputKeyE = 17
	KeyIntlRo               InputKeyE = 18
	KeyIntlYen              InputKeyE = 19
	KeyA                    InputKeyE = 20
	KeyB                    InputKeyE = 21
	KeyC                    InputKeyE = 22
	KeyD                    InputKeyE = 23
	KeyE                    InputKeyE = 24
	KeyF                    InputKeyE = 25
	KeyG                    InputKeyE = 26
	KeyH                    InputKeyE = 27
	KeyI                    InputKeyE = 28
	KeyJ                    InputKeyE = 29
	KeyK                    InputKeyE = 30
	KeyL                    InputKeyE = 31
	KeyM                    InputKeyE = 32
	KeyN                    InputKeyE = 33
	KeyO                    InputKeyE = 34
	KeyP                    InputKeyE = 35
	KeyQ                    InputKeyE = 36
	KeyR                    InputKeyE = 37
	KeyS                    InputKeyE = 38
	KeyT                    InputKeyE = 39
	KeyU                    InputKeyE = 40
	KeyV                    InputKeyE = 41
	KeyW                    InputKeyE = 42
	KeyX                    InputKeyE = 43
	KeyY                    InputKeyE = 44
	KeyZ                    InputKeyE = 45
	KeyMinus                InputKeyE = 46
	KeyPeriod               InputKeyE = 47
	KeyQuote                InputKeyE = 48
	KeySemicolon            InputKeyE = 49
	KeySlash                InputKeyE = 50
	KeyAltLeft              InputKeyE = 51
	KeyAltRight             InputKeyE = 52
	KeyBackspace            InputKeyE = 53
	KeyCapsLock             InputKeyE = 54
	KeyContextMenu          InputKeyE = 55
	KeyControlLeft          InputKeyE = 56
	KeyControlRight         InputKeyE = 57
	KeyEnter                InputKeyE = 58
	KeyMetaLeft             InputKeyE = 59
	KeyMetaRight            InputKeyE = 60
	KeyShiftLeft            InputKeyE = 61
	KeyShiftRight           InputKeyE = 62
	KeySpace                InputKeyE = 63
	KeyTab                  InputKeyE = 64
	KeyConvert              InputKeyE = 65
	KeyKanaMode             InputKeyE = 66
	KeyNonConvert           InputKeyE = 67
	KeyDelete               InputKeyE = 68
	KeyEnd                  InputKeyE = 69
	KeyHelp                 InputKeyE = 70
	KeyHome                 InputKeyE = 71
	KeyInsert               InputKeyE = 72
	KeyPageDown             InputKeyE = 73
	KeyPageUp               InputKeyE = 74
	KeyArrowDown            InputKeyE = 75
	KeyArrowLeft            InputKeyE = 76
	KeyArrowRight           InputKeyE = 77
	KeyArrowUp              InputKeyE = 78
	KeyNumLock              InputKeyE = 79
	KeyNumpad0              InputKeyE = 80
	KeyNumpad1              InputKeyE = 81
	KeyNumpad2              InputKeyE = 82
	KeyNumpad3              InputKeyE = 83
	KeyNumpad4              InputKeyE = 84
	KeyNumpad5              InputKeyE = 85
	KeyNumpad6              InputKeyE = 86
	KeyNumpad7              InputKeyE = 87
	KeyNumpad8              InputKeyE = 88
	KeyNumpad9              InputKeyE = 89
	KeyNumpadAdd            InputKeyE = 90
	KeyNumpadBackspace      InputKeyE = 91
	KeyNumpadClear          InputKeyE = 92
	KeyNumpadClearEntry     InputKeyE = 93
	KeyNumpadComma          InputKeyE = 94
	KeyNumpadDecimal        InputKeyE = 95
	KeyNumpadDivide         InputKeyE = 96
	KeyNumpadEnter          InputKeyE = 97
	KeyNumpadEqual          InputKeyE = 98
	KeyNumpadMemoryAdd      InputKeyE = 99
	KeyNumpadMemoryClear    InputKeyE = 100
	KeyNumpadMemoryRecall   InputKeyE = 101
	KeyNumpadMemoryStore    InputKeyE = 102
	KeyNumpadMemorySubtract InputKeyE = 103
	KeyNumpadMultiply       InputKeyE = 104
	KeyNumpadParenLeft      InputKeyE = 105
	KeyNumpadParenRight     InputKeyE = 106
	KeyNumpadSubtract       InputKeyE = 107
	KeyNumpadSeparator      InputKeyE = 108
	KeyNumpadUp             InputKeyE = 109
	KeyNumpadDown           InputKeyE = 110
	KeyNumpadRight          InputKeyE = 111
	KeyNumpadLeft           InputKeyE = 112
	KeyNumpadBegin          InputKeyE = 113
	KeyNumpadHome           InputKeyE = 114
	KeyNumpadEnd            InputKeyE = 115
	KeyNumpadInsert         InputKeyE = 116
	KeyNumpadDelete         InputKeyE = 117
	KeyNumpadPageUp         InputKeyE = 118
	KeyNumpadPageDown       InputKeyE = 119
	KeyEscape               InputKeyE = 120
	KeyF1                   InputKeyE = 121
	KeyF2                   InputKeyE = 122
	KeyF3                   InputKeyE = 123
	KeyF4                   InputKeyE = 124
	KeyF5                   InputKeyE = 125
	KeyF6                   InputKeyE = 126
	KeyF7                   InputKeyE = 127
	KeyF8                   InputKeyE = 128
	KeyF9                   InputKeyE = 129
	KeyF10                  InputKeyE = 130
	KeyF11                  InputKeyE = 131
	KeyF12                  InputKeyE = 132
	KeyF13                  InputKeyE = 133
	KeyF14                  InputKeyE = 134
	KeyF15                  InputKeyE = 135
	KeyF16                  InputKeyE = 136
	KeyF17                  InputKeyE = 137
	KeyF18                  InputKeyE = 138
	KeyF19                  InputKeyE = 139
	KeyF20                  InputKeyE = 140
	KeyF21                  InputKeyE = 141
	KeyF22                  InputKeyE = 142
	KeyF23                  InputKeyE = 143
	KeyF24                  InputKeyE = 144
	KeyF25                  InputKeyE = 145
	KeyFn                   InputKeyE = 146
	KeyFnLock               InputKeyE = 147
	KeyPrintScreen          InputKeyE = 148
	KeyScrollLock           InputKeyE = 149
	KeyPause                InputKeyE = 150
	KeyBrowserBack          InputKeyE = 151
	KeyBrowserFavorites     InputKeyE = 152
	KeyBrowserForward       InputKeyE = 153
	KeyBrowserHome          InputKeyE = 154
	KeyBrowserRefresh       InputKeyE = 155
	KeyBrowserSearch        InputKeyE = 156
	KeyBrowserStop          InputKeyE = 157
	KeyEject                InputKeyE = 158
	KeyLaunchApp1           InputKeyE = 159
	KeyLaunchApp2           InputKeyE = 160
	KeyLaunchMail           InputKeyE = 161
	KeyMediaPlayPause       InputKeyE = 162
	KeyMediaSelect          InputKeyE = 163
	KeyMediaStop            InputKeyE = 164
	KeyMediaTrackNext       InputKeyE = 165
	KeyMediaTrackPrevious   InputKeyE = 166
	KeyPower                InputKeyE = 167
	KeySleep                InputKeyE = 168
	KeyAudioVolumeDown      InputKeyE = 169
	KeyAudioVolumeMute      InputKeyE = 170
	KeyAudioVolumeUp        InputKeyE = 171
	KeyWakeUp               InputKeyE = 172
	KeyCopy                 InputKeyE = 173
	KeyCut                  InputKeyE = 174
	KeyPaste                InputKeyE = 175
)

const (
	ModsNone       InputMods = 0
	ModsShift      InputMods = 1
	ModsCtrl       InputMods = 2
	ModsAlt        InputMods = 4
	ModsSuper      InputMods = 8
	ModsCaps       InputMods = 16
	ModsNum        InputMods = 32
	ModsShiftRight InputMods = 64
	ModsCtrlRight  InputMods = 128
	ModsAltRight   InputMods = 256
	ModsSuperRight InputMods = 512
)

const (
	MouseUnknown InputMouseButton = 0
	MouseLeft    InputMouseButton = 1
	MouseRight   InputMouseButton = 2
	MouseMiddle  InputMouseButton = 3
	MouseFour    InputMouseButton = 4
	MouseFive    InputMouseButton = 5
	MouseSix     InputMouseButton = 6
	MouseSeven   InputMouseButton = 7
	MouseEight   InputMouseButton = 8
	MouseNine    InputMouseButton = 9
	MouseTen     InputMouseButton = 10
	MouseEleven  InputMouseButton = 11
)

const (
	MouseRelease InputMouseState = 0
	MousePress   InputMouseState = 1
)

const (
	TriggerPhysical InputTriggerTag = 0
	TriggerUnicode  InputTriggerTag = 1
	TriggerCatchAll InputTriggerTag = 2
)

const (
	PlatformInvalid PlatformE = 0
	PlatformMacos   PlatformE = 1
	PlatformIos     PlatformE = 2
)

const (
	PointCoordExact       PointCoord = 0
	PointCoordTopLeft     PointCoord = 1
	PointCoordBottomRight PointCoord = 2
)

const (
	PointActive   PointTag = 0
	PointViewport PointTag = 1
	PointScreen   PointTag = 2
	PointSurface  PointTag = 3
)

const (
	SurfaceContextWindow SurfaceContext = 0
	SurfaceContextTab    SurfaceContext = 1
	SurfaceContextSplit  SurfaceContext = 2
)

const (
	TargetApp     TargetTag = 0
	TargetSurface TargetTag = 1
)

const Success = 0
