// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

const (
	ActionCloseTabModeThis  ActionCloseTabMode = 0
	ActionCloseTabModeOther ActionCloseTabMode = 1
	ActionCloseTabModeRight ActionCloseTabMode = 2
)

const (
	ActionColorKindForeground ActionColorKind = -1
	ActionColorKindBackground ActionColorKind = -2
	ActionColorKindCursor     ActionColorKind = -3
)

const (
	FloatWindowOn     ActionFloatWindow = 0
	FloatWindowOff    ActionFloatWindow = 1
	FloatWindowToggle ActionFloatWindow = 2
)

const (
	FullscreenNative                    ActionFullscreen = 0
	FullscreenMacOSNonNative            ActionFullscreen = 1
	FullscreenMacOSNonNativeVisibleMenu ActionFullscreen = 2
	FullscreenMacOSNonNativePaddedNotch ActionFullscreen = 3
)

const (
	GotoSplitPrevious ActionGotoSplit = 0
	GotoSplitNext     ActionGotoSplit = 1
	GotoSplitUp       ActionGotoSplit = 2
	GotoSplitLeft     ActionGotoSplit = 3
	GotoSplitDown     ActionGotoSplit = 4
	GotoSplitRight    ActionGotoSplit = 5
)

const (
	GotoTabPrevious ActionGotoTab = -1
	GotoTabNext     ActionGotoTab = -2
	GotoTabLast     ActionGotoTab = -3
)

const (
	GotoWindowPrevious ActionGotoWindow = 0
	GotoWindowNext     ActionGotoWindow = 1
)

const (
	InspectorToggle ActionInspector = 0
	InspectorShow   ActionInspector = 1
	InspectorHide   ActionInspector = 2
)

const (
	KeyTableActivate      ActionKeyTableTag = 0
	KeyTableDeactivate    ActionKeyTableTag = 1
	KeyTableDeactivateAll ActionKeyTableTag = 2
)

const (
	MouseShapeDefault      ActionMouseShape = 0
	MouseShapeContextMenu  ActionMouseShape = 1
	MouseShapeHelp         ActionMouseShape = 2
	MouseShapePointer      ActionMouseShape = 3
	MouseShapeProgress     ActionMouseShape = 4
	MouseShapeWait         ActionMouseShape = 5
	MouseShapeCell         ActionMouseShape = 6
	MouseShapeCrosshair    ActionMouseShape = 7
	MouseShapeText         ActionMouseShape = 8
	MouseShapeVerticalText ActionMouseShape = 9
	MouseShapeAlias        ActionMouseShape = 10
	MouseShapeCopy         ActionMouseShape = 11
	MouseShapeMove         ActionMouseShape = 12
	MouseShapeNoDrop       ActionMouseShape = 13
	MouseShapeNotAllowed   ActionMouseShape = 14
	MouseShapeGrab         ActionMouseShape = 15
	MouseShapeGrabbing     ActionMouseShape = 16
	MouseShapeAllScroll    ActionMouseShape = 17
	MouseShapeColResize    ActionMouseShape = 18
	MouseShapeRowResize    ActionMouseShape = 19
	MouseShapeNResize      ActionMouseShape = 20
	MouseShapeEResize      ActionMouseShape = 21
	MouseShapeSResize      ActionMouseShape = 22
	MouseShapeWResize      ActionMouseShape = 23
	MouseShapeNeResize     ActionMouseShape = 24
	MouseShapeNwResize     ActionMouseShape = 25
	MouseShapeSeResize     ActionMouseShape = 26
	MouseShapeSwResize     ActionMouseShape = 27
	MouseShapeEwResize     ActionMouseShape = 28
	MouseShapeNsResize     ActionMouseShape = 29
	MouseShapeNeswResize   ActionMouseShape = 30
	MouseShapeNwseResize   ActionMouseShape = 31
	MouseShapeZoomIn       ActionMouseShape = 32
	MouseShapeZoomOut      ActionMouseShape = 33
)

const (
	MouseVisible ActionMouseVisibility = 0
	MouseHidden  ActionMouseVisibility = 1
)

const (
	ActionOpenURLKindUnknown ActionOpenURLKind = 0
	ActionOpenURLKindText    ActionOpenURLKind = 1
	ActionOpenURLKindHTML    ActionOpenURLKind = 2
)

const (
	ProgressStateRemove        ActionProgressReportState = 0
	ProgressStateSet           ActionProgressReportState = 1
	ProgressStateError         ActionProgressReportState = 2
	ProgressStateIndeterminate ActionProgressReportState = 3
	ProgressStatePause         ActionProgressReportState = 4
)

const (
	PromptTitleSurface ActionPromptTitle = 0
	PromptTitleTab     ActionPromptTitle = 1
)

const (
	QuitTimerStart ActionQuitTimer = 0
	QuitTimerStop  ActionQuitTimer = 1
)

const (
	ReadonlyOff ActionReadonly = 0
	ReadonlyOn  ActionReadonly = 1
)

const (
	RendererHealthHealthy   ActionRendererHealth = 0
	RendererHealthUnhealthy ActionRendererHealth = 1
)

const (
	ResizeSplitUp    ActionResizeSplitDirection = 0
	ResizeSplitDown  ActionResizeSplitDirection = 1
	ResizeSplitLeft  ActionResizeSplitDirection = 2
	ResizeSplitRight ActionResizeSplitDirection = 3
)

const (
	SecureInputOn     ActionSecureInput = 0
	SecureInputOff    ActionSecureInput = 1
	SecureInputToggle ActionSecureInput = 2
)

const (
	SplitDirectionRight ActionSplitDirection = 0
	SplitDirectionDown  ActionSplitDirection = 1
	SplitDirectionLeft  ActionSplitDirection = 2
	SplitDirectionUp    ActionSplitDirection = 3
)

const (
	ActionQuit                     ActionTag = 0
	ActionNewWindow                ActionTag = 1
	ActionNewTab                   ActionTag = 2
	ActionCloseTab                 ActionTag = 3
	ActionNewSplit                 ActionTag = 4
	ActionCloseAllWindows          ActionTag = 5
	ActionToggleMaximize           ActionTag = 6
	ActionToggleFullscreen         ActionTag = 7
	ActionToggleTabOverview        ActionTag = 8
	ActionToggleWindowDecorations  ActionTag = 9
	ActionToggleQuickTerminal      ActionTag = 10
	ActionToggleCommandPalette     ActionTag = 11
	ActionToggleVisibility         ActionTag = 12
	ActionToggleBackgroundOpacity  ActionTag = 13
	ActionMoveTabValue             ActionTag = 14
	ActionGotoTabValue             ActionTag = 15
	ActionGotoSplitValue           ActionTag = 16
	ActionGotoWindowValue          ActionTag = 17
	ActionResizeSplitValue         ActionTag = 18
	ActionEqualizeSplits           ActionTag = 19
	ActionToggleSplitZoom          ActionTag = 20
	ActionPresentTerminal          ActionTag = 21
	ActionSizeLimitValue           ActionTag = 22
	ActionResetWindowSize          ActionTag = 23
	ActionInitialSizeValue         ActionTag = 24
	ActionCellSizeValue            ActionTag = 25
	ActionScrollbarValue           ActionTag = 26
	ActionRender                   ActionTag = 27
	ActionInspectorValue           ActionTag = 28
	ActionShowGtkInspector         ActionTag = 29
	ActionRenderInspector          ActionTag = 30
	ActionDesktopNotificationValue ActionTag = 31
	ActionSetTitleValue            ActionTag = 32
	ActionSetTabTitle              ActionTag = 33
	ActionPromptTitleValue         ActionTag = 34
	ActionPwdValue                 ActionTag = 35
	ActionMouseShapeValue          ActionTag = 36
	ActionMouseVisibilityValue     ActionTag = 37
	ActionMouseOverLinkValue       ActionTag = 38
	ActionRendererHealthValue      ActionTag = 39
	ActionOpenConfig               ActionTag = 40
	ActionQuitTimerValue           ActionTag = 41
	ActionFloatWindowValue         ActionTag = 42
	ActionSecureInputValue         ActionTag = 43
	ActionKeySequenceValue         ActionTag = 44
	ActionKeyTableValue            ActionTag = 45
	ActionColorChangeValue         ActionTag = 46
	ActionReloadConfigValue        ActionTag = 47
	ActionConfigChangeValue        ActionTag = 48
	ActionCloseWindow              ActionTag = 49
	ActionRingBell                 ActionTag = 50
	ActionSelectionChanged         ActionTag = 51
	ActionUndo                     ActionTag = 52
	ActionRedo                     ActionTag = 53
	ActionCheckForUpdates          ActionTag = 54
	ActionOpenURLValue             ActionTag = 55
	ActionShowChildExited          ActionTag = 56
	ActionProgressReportValue      ActionTag = 57
	ActionShowOnScreenKeyboard     ActionTag = 58
	ActionCommandFinishedValue     ActionTag = 59
	ActionStartSearchValue         ActionTag = 60
	ActionEndSearch                ActionTag = 61
	ActionSearchTotalValue         ActionTag = 62
	ActionSearchSelectedValue      ActionTag = 63
	ActionReadonlyValue            ActionTag = 64
	ActionCopyTitleToClipboard     ActionTag = 65
)

const (
	BindingFlagsConsumed    BindingFlags = 1
	BindingFlagsAll         BindingFlags = 2
	BindingFlagsGlobal      BindingFlags = 4
	BindingFlagsPerformable BindingFlags = 8
)

const (
	BuildModeDebug        BuildMode = 0
	BuildModeReleaseSafe  BuildMode = 1
	BuildModeReleaseFast  BuildMode = 2
	BuildModeReleaseSmall BuildMode = 3
)

const (
	ClipboardStandard  Clipboard = 0
	ClipboardSelection Clipboard = 1
)

const (
	ClipboardRequestPaste      ClipboardRequest = 0
	ClipboardRequestOsc52Read  ClipboardRequest = 1
	ClipboardRequestOsc52Write ClipboardRequest = 2
)

const (
	ColorSchemeLight ColorScheme = 0
	ColorSchemeDark  ColorScheme = 1
)

const (
	ActionRelease InputAction = 0
	ActionPress   InputAction = 1
	ActionRepeat  InputAction = 2
)

const (
	KeyUnidentified         InputKey = 0
	KeyBackquote            InputKey = 1
	KeyBackslash            InputKey = 2
	KeyBracketLeft          InputKey = 3
	KeyBracketRight         InputKey = 4
	KeyComma                InputKey = 5
	KeyDigit0               InputKey = 6
	KeyDigit1               InputKey = 7
	KeyDigit2               InputKey = 8
	KeyDigit3               InputKey = 9
	KeyDigit4               InputKey = 10
	KeyDigit5               InputKey = 11
	KeyDigit6               InputKey = 12
	KeyDigit7               InputKey = 13
	KeyDigit8               InputKey = 14
	KeyDigit9               InputKey = 15
	KeyEqual                InputKey = 16
	KeyIntlBackslash        InputKey = 17
	KeyIntlRo               InputKey = 18
	KeyIntlYen              InputKey = 19
	KeyA                    InputKey = 20
	KeyB                    InputKey = 21
	KeyC                    InputKey = 22
	KeyD                    InputKey = 23
	KeyE                    InputKey = 24
	KeyF                    InputKey = 25
	KeyG                    InputKey = 26
	KeyH                    InputKey = 27
	KeyI                    InputKey = 28
	KeyJ                    InputKey = 29
	KeyK                    InputKey = 30
	KeyL                    InputKey = 31
	KeyM                    InputKey = 32
	KeyN                    InputKey = 33
	KeyO                    InputKey = 34
	KeyP                    InputKey = 35
	KeyQ                    InputKey = 36
	KeyR                    InputKey = 37
	KeyS                    InputKey = 38
	KeyT                    InputKey = 39
	KeyU                    InputKey = 40
	KeyV                    InputKey = 41
	KeyW                    InputKey = 42
	KeyX                    InputKey = 43
	KeyY                    InputKey = 44
	KeyZ                    InputKey = 45
	KeyMinus                InputKey = 46
	KeyPeriod               InputKey = 47
	KeyQuote                InputKey = 48
	KeySemicolon            InputKey = 49
	KeySlash                InputKey = 50
	KeyAltLeft              InputKey = 51
	KeyAltRight             InputKey = 52
	KeyBackspace            InputKey = 53
	KeyCapsLock             InputKey = 54
	KeyContextMenu          InputKey = 55
	KeyControlLeft          InputKey = 56
	KeyControlRight         InputKey = 57
	KeyEnter                InputKey = 58
	KeyMetaLeft             InputKey = 59
	KeyMetaRight            InputKey = 60
	KeyShiftLeft            InputKey = 61
	KeyShiftRight           InputKey = 62
	KeySpace                InputKey = 63
	KeyTab                  InputKey = 64
	KeyConvert              InputKey = 65
	KeyKanaMode             InputKey = 66
	KeyNonConvert           InputKey = 67
	KeyDelete               InputKey = 68
	KeyEnd                  InputKey = 69
	KeyHelp                 InputKey = 70
	KeyHome                 InputKey = 71
	KeyInsert               InputKey = 72
	KeyPageDown             InputKey = 73
	KeyPageUp               InputKey = 74
	KeyArrowDown            InputKey = 75
	KeyArrowLeft            InputKey = 76
	KeyArrowRight           InputKey = 77
	KeyArrowUp              InputKey = 78
	KeyNumLock              InputKey = 79
	KeyNumpad0              InputKey = 80
	KeyNumpad1              InputKey = 81
	KeyNumpad2              InputKey = 82
	KeyNumpad3              InputKey = 83
	KeyNumpad4              InputKey = 84
	KeyNumpad5              InputKey = 85
	KeyNumpad6              InputKey = 86
	KeyNumpad7              InputKey = 87
	KeyNumpad8              InputKey = 88
	KeyNumpad9              InputKey = 89
	KeyNumpadAdd            InputKey = 90
	KeyNumpadBackspace      InputKey = 91
	KeyNumpadClear          InputKey = 92
	KeyNumpadClearEntry     InputKey = 93
	KeyNumpadComma          InputKey = 94
	KeyNumpadDecimal        InputKey = 95
	KeyNumpadDivide         InputKey = 96
	KeyNumpadEnter          InputKey = 97
	KeyNumpadEqual          InputKey = 98
	KeyNumpadMemoryAdd      InputKey = 99
	KeyNumpadMemoryClear    InputKey = 100
	KeyNumpadMemoryRecall   InputKey = 101
	KeyNumpadMemoryStore    InputKey = 102
	KeyNumpadMemorySubtract InputKey = 103
	KeyNumpadMultiply       InputKey = 104
	KeyNumpadParenLeft      InputKey = 105
	KeyNumpadParenRight     InputKey = 106
	KeyNumpadSubtract       InputKey = 107
	KeyNumpadSeparator      InputKey = 108
	KeyNumpadUp             InputKey = 109
	KeyNumpadDown           InputKey = 110
	KeyNumpadRight          InputKey = 111
	KeyNumpadLeft           InputKey = 112
	KeyNumpadBegin          InputKey = 113
	KeyNumpadHome           InputKey = 114
	KeyNumpadEnd            InputKey = 115
	KeyNumpadInsert         InputKey = 116
	KeyNumpadDelete         InputKey = 117
	KeyNumpadPageUp         InputKey = 118
	KeyNumpadPageDown       InputKey = 119
	KeyEscape               InputKey = 120
	KeyF1                   InputKey = 121
	KeyF2                   InputKey = 122
	KeyF3                   InputKey = 123
	KeyF4                   InputKey = 124
	KeyF5                   InputKey = 125
	KeyF6                   InputKey = 126
	KeyF7                   InputKey = 127
	KeyF8                   InputKey = 128
	KeyF9                   InputKey = 129
	KeyF10                  InputKey = 130
	KeyF11                  InputKey = 131
	KeyF12                  InputKey = 132
	KeyF13                  InputKey = 133
	KeyF14                  InputKey = 134
	KeyF15                  InputKey = 135
	KeyF16                  InputKey = 136
	KeyF17                  InputKey = 137
	KeyF18                  InputKey = 138
	KeyF19                  InputKey = 139
	KeyF20                  InputKey = 140
	KeyF21                  InputKey = 141
	KeyF22                  InputKey = 142
	KeyF23                  InputKey = 143
	KeyF24                  InputKey = 144
	KeyF25                  InputKey = 145
	KeyFn                   InputKey = 146
	KeyFnLock               InputKey = 147
	KeyPrintScreen          InputKey = 148
	KeyScrollLock           InputKey = 149
	KeyPause                InputKey = 150
	KeyBrowserBack          InputKey = 151
	KeyBrowserFavorites     InputKey = 152
	KeyBrowserForward       InputKey = 153
	KeyBrowserHome          InputKey = 154
	KeyBrowserRefresh       InputKey = 155
	KeyBrowserSearch        InputKey = 156
	KeyBrowserStop          InputKey = 157
	KeyEject                InputKey = 158
	KeyLaunchApp1           InputKey = 159
	KeyLaunchApp2           InputKey = 160
	KeyLaunchMail           InputKey = 161
	KeyMediaPlayPause       InputKey = 162
	KeyMediaSelect          InputKey = 163
	KeyMediaStop            InputKey = 164
	KeyMediaTrackNext       InputKey = 165
	KeyMediaTrackPrevious   InputKey = 166
	KeyPower                InputKey = 167
	KeySleep                InputKey = 168
	KeyAudioVolumeDown      InputKey = 169
	KeyAudioVolumeMute      InputKey = 170
	KeyAudioVolumeUp        InputKey = 171
	KeyWakeUp               InputKey = 172
	KeyCopy                 InputKey = 173
	KeyCut                  InputKey = 174
	KeyPaste                InputKey = 175
)

const (
	ModsNone       InputMods = 0
	ModsShift      InputMods = 1
	ModsCtrl       InputMods = 2
	ModsAlt        InputMods = 4
	ModsSuper      InputMods = 8
	ModsCaps       InputMods = 16
	ModsNum        InputMods = 32
	ModsShiftRight InputMods = 64
	ModsCtrlRight  InputMods = 128
	ModsAltRight   InputMods = 256
	ModsSuperRight InputMods = 512
)

const (
	MouseUnknown InputMouseButton = 0
	MouseLeft    InputMouseButton = 1
	MouseRight   InputMouseButton = 2
	MouseMiddle  InputMouseButton = 3
	MouseFour    InputMouseButton = 4
	MouseFive    InputMouseButton = 5
	MouseSix     InputMouseButton = 6
	MouseSeven   InputMouseButton = 7
	MouseEight   InputMouseButton = 8
	MouseNine    InputMouseButton = 9
	MouseTen     InputMouseButton = 10
	MouseEleven  InputMouseButton = 11
)

const (
	MouseRelease InputMouseState = 0
	MousePress   InputMouseState = 1
)

const (
	TriggerPhysical InputTriggerTag = 0
	TriggerUnicode  InputTriggerTag = 1
	TriggerCatchAll InputTriggerTag = 2
)

const (
	PlatformInvalid    Platform = 0
	PlatformMacOSValue Platform = 1
	PlatformIOSValue   Platform = 2
)

const (
	PointCoordExact       PointCoord = 0
	PointCoordTopLeft     PointCoord = 1
	PointCoordBottomRight PointCoord = 2
)

const (
	PointActive   PointTag = 0
	PointViewport PointTag = 1
	PointScreen   PointTag = 2
	PointSurface  PointTag = 3
)

const (
	SurfaceContextWindow SurfaceContext = 0
	SurfaceContextTab    SurfaceContext = 1
	SurfaceContextSplit  SurfaceContext = 2
)

const (
	TargetApp     TargetTag = 0
	TargetSurface TargetTag = 1
)

const Success = 0
