// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import "unsafe"

var AppFree func(AppHandle)

var AppHasGlobalKeybinds func(AppHandle) bool

var AppKey func(AppHandle, InputKeyS) bool

var AppKeyboardChanged func(AppHandle)

var AppNeedsConfirmQuit func(AppHandle) bool

var AppNew func(*RuntimeConfig, ConfigHandle) AppHandle

var AppOpenConfig func(AppHandle)

var AppSetColorScheme func(AppHandle, ColorScheme)

var AppSetFocus func(AppHandle, bool)

var AppTick func(AppHandle)

var AppUpdateConfig func(AppHandle, ConfigHandle)

var AppUserdata func(AppHandle) unsafe.Pointer

var BenchmarkCLI func(*byte, *byte) bool

var CLITryAction func()

var ConfigClone func(ConfigHandle) ConfigHandle

var ConfigDiagnosticsCount func(ConfigHandle) uint32

var ConfigFinalize func(ConfigHandle)

var ConfigFree func(ConfigHandle)

var ConfigGet func(ConfigHandle, unsafe.Pointer, *byte, uintptr) bool

var ConfigGetDiagnostic func(ConfigHandle, uint32) Diagnostic

var ConfigKeyIsBinding func(ConfigHandle, InputKeyS) bool

var ConfigLoadCLIArgs func(ConfigHandle)

var ConfigLoadDefaultFiles func(ConfigHandle)

var ConfigLoadFile func(ConfigHandle, *byte)

var ConfigLoadRecursiveFiles func(ConfigHandle)

var ConfigNew func() ConfigHandle

var ConfigOpenPath func() String

var ConfigTrigger func(ConfigHandle, *byte, uintptr) InputTrigger

var Info func() InfoS

var Init func(uintptr, **byte) int32

var InspectorFree func(SurfaceHandle)

var InspectorKey func(InspectorHandle, InputAction, InputKeyE, InputMods)

var InspectorMouseButton func(InspectorHandle, InputMouseState, InputMouseButton, InputMods)

var InspectorMousePos func(InspectorHandle, float64, float64)

var InspectorMouseScroll func(InspectorHandle, float64, float64, InputScrollMods)

var InspectorSetContentScale func(InspectorHandle, float64, float64)

var InspectorSetFocus func(InspectorHandle, bool)

var InspectorSetSize func(InspectorHandle, uint32, uint32)

var InspectorText func(InspectorHandle, *byte)

var SetWindowBackgroundBlur func(AppHandle, unsafe.Pointer)

var StringFree func(String)

var SurfaceApp func(SurfaceHandle) AppHandle

var SurfaceBindingAction func(SurfaceHandle, *byte, uintptr) bool

var SurfaceCompleteClipboardRequest func(SurfaceHandle, *byte, unsafe.Pointer, bool)

var SurfaceConfigNew func() SurfaceConfig

var SurfaceDraw func(SurfaceHandle)

var SurfaceForegroundPid func(SurfaceHandle) uint64

var SurfaceFree func(SurfaceHandle)

var SurfaceFreeText func(SurfaceHandle, *Text)

var SurfaceHasSelection func(SurfaceHandle) bool

var SurfaceIMEPoint func(SurfaceHandle, *float64, *float64, *float64, *float64)

var SurfaceInheritedConfig func(SurfaceHandle, SurfaceContext) SurfaceConfig

var SurfaceInspector func(SurfaceHandle) InspectorHandle

var SurfaceKey func(SurfaceHandle, InputKeyS) bool

var SurfaceKeyIsBinding func(SurfaceHandle, InputKeyS, *BindingFlags) bool

var SurfaceKeyTranslationMods func(SurfaceHandle, InputMods) InputMods

var SurfaceMouseButton func(SurfaceHandle, InputMouseState, InputMouseButton, InputMods) bool

var SurfaceMouseCaptured func(SurfaceHandle) bool

var SurfaceMousePos func(SurfaceHandle, float64, float64, InputMods)

var SurfaceMousePressure func(SurfaceHandle, uint32, float64)

var SurfaceMouseScroll func(SurfaceHandle, float64, float64, InputScrollMods)

var SurfaceNeedsConfirmQuit func(SurfaceHandle) bool

var SurfaceNew func(AppHandle, *SurfaceConfig) SurfaceHandle

var SurfacePreedit func(SurfaceHandle, *byte, uintptr)

var SurfaceProcessExited func(SurfaceHandle) bool

var SurfaceReadSelection func(SurfaceHandle, *Text) bool

var SurfaceReadText func(SurfaceHandle, Selection, *Text) bool

var SurfaceRefresh func(SurfaceHandle)

var SurfaceRequestClose func(SurfaceHandle)

var SurfaceSetColorScheme func(SurfaceHandle, ColorScheme)

var SurfaceSetContentScale func(SurfaceHandle, float64, float64)

var SurfaceSetFocus func(SurfaceHandle, bool)

var SurfaceSetOcclusion func(SurfaceHandle, bool)

var SurfaceSetSize func(SurfaceHandle, uint32, uint32)

var SurfaceSize func(SurfaceHandle) SurfaceSizeS

var SurfaceSplit func(SurfaceHandle, ActionSplitDirection)

var SurfaceSplitEqualize func(SurfaceHandle)

var SurfaceSplitFocus func(SurfaceHandle, ActionGotoSplitE)

var SurfaceSplitResize func(SurfaceHandle, ActionResizeSplitDirection, uint16)

var SurfaceText func(SurfaceHandle, *byte, uintptr)

var SurfaceTTYName func(SurfaceHandle) String

var SurfaceUpdateConfig func(SurfaceHandle, ConfigHandle)

var SurfaceUserdata func(SurfaceHandle) unsafe.Pointer

var Translate func(*byte) *byte
