// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import (
	"fmt"
	"github.com/bnema/purego"
	"unsafe"
)

var allSymbols = []string{
	"ghostty_app_free",
	"ghostty_app_has_global_keybinds",
	"ghostty_app_key",
	"ghostty_app_keyboard_changed",
	"ghostty_app_needs_confirm_quit",
	"ghostty_app_new",
	"ghostty_app_open_config",
	"ghostty_app_set_color_scheme",
	"ghostty_app_set_focus",
	"ghostty_app_tick",
	"ghostty_app_update_config",
	"ghostty_app_userdata",
	"ghostty_benchmark_cli",
	"ghostty_cli_try_action",
	"ghostty_config_clone",
	"ghostty_config_diagnostics_count",
	"ghostty_config_finalize",
	"ghostty_config_free",
	"ghostty_config_get",
	"ghostty_config_get_diagnostic",
	"ghostty_config_key_is_binding",
	"ghostty_config_load_cli_args",
	"ghostty_config_load_default_files",
	"ghostty_config_load_file",
	"ghostty_config_load_recursive_files",
	"ghostty_config_new",
	"ghostty_config_open_path",
	"ghostty_config_trigger",
	"ghostty_info",
	"ghostty_init",
	"ghostty_inspector_free",
	"ghostty_inspector_key",
	"ghostty_inspector_mouse_button",
	"ghostty_inspector_mouse_pos",
	"ghostty_inspector_mouse_scroll",
	"ghostty_inspector_set_content_scale",
	"ghostty_inspector_set_focus",
	"ghostty_inspector_set_size",
	"ghostty_inspector_text",
	"ghostty_set_window_background_blur",
	"ghostty_string_free",
	"ghostty_surface_app",
	"ghostty_surface_binding_action",
	"ghostty_surface_complete_clipboard_request",
	"ghostty_surface_config_new",
	"ghostty_surface_draw",
	"ghostty_surface_foreground_pid",
	"ghostty_surface_free",
	"ghostty_surface_free_text",
	"ghostty_surface_has_selection",
	"ghostty_surface_ime_point",
	"ghostty_surface_inherited_config",
	"ghostty_surface_inspector",
	"ghostty_surface_key",
	"ghostty_surface_key_is_binding",
	"ghostty_surface_key_translation_mods",
	"ghostty_surface_mouse_button",
	"ghostty_surface_mouse_captured",
	"ghostty_surface_mouse_pos",
	"ghostty_surface_mouse_pressure",
	"ghostty_surface_mouse_scroll",
	"ghostty_surface_needs_confirm_quit",
	"ghostty_surface_new",
	"ghostty_surface_preedit",
	"ghostty_surface_process_exited",
	"ghostty_surface_read_selection",
	"ghostty_surface_read_text",
	"ghostty_surface_refresh",
	"ghostty_surface_request_close",
	"ghostty_surface_set_color_scheme",
	"ghostty_surface_set_content_scale",
	"ghostty_surface_set_focus",
	"ghostty_surface_set_occlusion",
	"ghostty_surface_set_size",
	"ghostty_surface_size",
	"ghostty_surface_split",
	"ghostty_surface_split_equalize",
	"ghostty_surface_split_focus",
	"ghostty_surface_split_resize",
	"ghostty_surface_text",
	"ghostty_surface_tty_name",
	"ghostty_surface_update_config",
	"ghostty_surface_userdata",
	"ghostty_translate",
}

func register(handle uintptr) error {
	return registerWith(handle, purego.Dlsym, purego.RegisterFunc)
}

func registerWith(handle uintptr, resolve func(uintptr, string) (uintptr, error), registerFunction func(any, uintptr)) (err error) {
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("register function: %v", recovered)
		}
	}()
	addresses := make(map[string]uintptr, len(allSymbols))
	for _, symbol := range allSymbols {
		address, resolveErr := resolve(handle, symbol)
		if resolveErr != nil {
			return fmt.Errorf("resolve %s: %w", symbol, resolveErr)
		}
		addresses[symbol] = address
	}
	var registeredAppFree func(AppHandle)
	var registeredAppHasGlobalKeybinds func(AppHandle) bool
	var registeredAppKey func(AppHandle, InputKeyS) bool
	var registeredAppKeyboardChanged func(AppHandle)
	var registeredAppNeedsConfirmQuit func(AppHandle) bool
	var registeredAppNew func(*RuntimeConfig, ConfigHandle) AppHandle
	var registeredAppOpenConfig func(AppHandle)
	var registeredAppSetColorScheme func(AppHandle, ColorScheme)
	var registeredAppSetFocus func(AppHandle, bool)
	var registeredAppTick func(AppHandle)
	var registeredAppUpdateConfig func(AppHandle, ConfigHandle)
	var registeredAppUserdata func(AppHandle) unsafe.Pointer
	var registeredBenchmarkCLI func(*byte, *byte) bool
	var registeredCLITryAction func()
	var registeredConfigClone func(ConfigHandle) ConfigHandle
	var registeredConfigDiagnosticsCount func(ConfigHandle) uint32
	var registeredConfigFinalize func(ConfigHandle)
	var registeredConfigFree func(ConfigHandle)
	var registeredConfigGet func(ConfigHandle, unsafe.Pointer, *byte, uintptr) bool
	var registeredConfigGetDiagnostic func(ConfigHandle, uint32) Diagnostic
	var registeredConfigKeyIsBinding func(ConfigHandle, InputKeyS) bool
	var registeredConfigLoadCLIArgs func(ConfigHandle)
	var registeredConfigLoadDefaultFiles func(ConfigHandle)
	var registeredConfigLoadFile func(ConfigHandle, *byte)
	var registeredConfigLoadRecursiveFiles func(ConfigHandle)
	var registeredConfigNew func() ConfigHandle
	var registeredConfigOpenPath func() String
	var registeredConfigTrigger func(ConfigHandle, *byte, uintptr) InputTrigger
	var registeredInfoValue func() Info
	var registeredInit func(uintptr, **byte) int32
	var registeredInspectorFree func(SurfaceHandle)
	var registeredInspectorKey func(InspectorHandle, InputAction, InputKey, InputMods)
	var registeredInspectorMouseButton func(InspectorHandle, InputMouseState, InputMouseButton, InputMods)
	var registeredInspectorMousePos func(InspectorHandle, float64, float64)
	var registeredInspectorMouseScroll func(InspectorHandle, float64, float64, InputScrollMods)
	var registeredInspectorSetContentScale func(InspectorHandle, float64, float64)
	var registeredInspectorSetFocus func(InspectorHandle, bool)
	var registeredInspectorSetSize func(InspectorHandle, uint32, uint32)
	var registeredInspectorText func(InspectorHandle, *byte)
	var registeredSetWindowBackgroundBlur func(AppHandle, unsafe.Pointer)
	var registeredStringFree func(String)
	var registeredSurfaceApp func(SurfaceHandle) AppHandle
	var registeredSurfaceBindingAction func(SurfaceHandle, *byte, uintptr) bool
	var registeredSurfaceCompleteClipboardRequest func(SurfaceHandle, *byte, unsafe.Pointer, bool)
	var registeredSurfaceConfigNew func() SurfaceConfig
	var registeredSurfaceDraw func(SurfaceHandle)
	var registeredSurfaceForegroundPid func(SurfaceHandle) uint64
	var registeredSurfaceFree func(SurfaceHandle)
	var registeredSurfaceFreeText func(SurfaceHandle, *Text)
	var registeredSurfaceHasSelection func(SurfaceHandle) bool
	var registeredSurfaceIMEPoint func(SurfaceHandle, *float64, *float64, *float64, *float64)
	var registeredSurfaceInheritedConfig func(SurfaceHandle, SurfaceContext) SurfaceConfig
	var registeredSurfaceInspector func(SurfaceHandle) InspectorHandle
	var registeredSurfaceKey func(SurfaceHandle, InputKeyS) bool
	var registeredSurfaceKeyIsBinding func(SurfaceHandle, InputKeyS, *BindingFlags) bool
	var registeredSurfaceKeyTranslationMods func(SurfaceHandle, InputMods) InputMods
	var registeredSurfaceMouseButton func(SurfaceHandle, InputMouseState, InputMouseButton, InputMods) bool
	var registeredSurfaceMouseCaptured func(SurfaceHandle) bool
	var registeredSurfaceMousePos func(SurfaceHandle, float64, float64, InputMods)
	var registeredSurfaceMousePressure func(SurfaceHandle, uint32, float64)
	var registeredSurfaceMouseScroll func(SurfaceHandle, float64, float64, InputScrollMods)
	var registeredSurfaceNeedsConfirmQuit func(SurfaceHandle) bool
	var registeredSurfaceNew func(AppHandle, *SurfaceConfig) SurfaceHandle
	var registeredSurfacePreedit func(SurfaceHandle, *byte, uintptr)
	var registeredSurfaceProcessExited func(SurfaceHandle) bool
	var registeredSurfaceReadSelection func(SurfaceHandle, *Text) bool
	var registeredSurfaceReadText func(SurfaceHandle, Selection, *Text) bool
	var registeredSurfaceRefresh func(SurfaceHandle)
	var registeredSurfaceRequestClose func(SurfaceHandle)
	var registeredSurfaceSetColorScheme func(SurfaceHandle, ColorScheme)
	var registeredSurfaceSetContentScale func(SurfaceHandle, float64, float64)
	var registeredSurfaceSetFocus func(SurfaceHandle, bool)
	var registeredSurfaceSetOcclusion func(SurfaceHandle, bool)
	var registeredSurfaceSetSize func(SurfaceHandle, uint32, uint32)
	var registeredSurfaceSizeValue func(SurfaceHandle) SurfaceSize
	var registeredSurfaceSplit func(SurfaceHandle, ActionSplitDirection)
	var registeredSurfaceSplitEqualize func(SurfaceHandle)
	var registeredSurfaceSplitFocus func(SurfaceHandle, ActionGotoSplit)
	var registeredSurfaceSplitResize func(SurfaceHandle, ActionResizeSplitDirection, uint16)
	var registeredSurfaceText func(SurfaceHandle, *byte, uintptr)
	var registeredSurfaceTTYName func(SurfaceHandle) String
	var registeredSurfaceUpdateConfig func(SurfaceHandle, ConfigHandle)
	var registeredSurfaceUserdata func(SurfaceHandle) unsafe.Pointer
	var registeredTranslate func(*byte) *byte

	registerFunction(&registeredAppFree, addresses["ghostty_app_free"])
	registerFunction(&registeredAppHasGlobalKeybinds, addresses["ghostty_app_has_global_keybinds"])
	registerFunction(&registeredAppKey, addresses["ghostty_app_key"])
	registerFunction(&registeredAppKeyboardChanged, addresses["ghostty_app_keyboard_changed"])
	registerFunction(&registeredAppNeedsConfirmQuit, addresses["ghostty_app_needs_confirm_quit"])
	registerFunction(&registeredAppNew, addresses["ghostty_app_new"])
	registerFunction(&registeredAppOpenConfig, addresses["ghostty_app_open_config"])
	registerFunction(&registeredAppSetColorScheme, addresses["ghostty_app_set_color_scheme"])
	registerFunction(&registeredAppSetFocus, addresses["ghostty_app_set_focus"])
	registerFunction(&registeredAppTick, addresses["ghostty_app_tick"])
	registerFunction(&registeredAppUpdateConfig, addresses["ghostty_app_update_config"])
	registerFunction(&registeredAppUserdata, addresses["ghostty_app_userdata"])
	registerFunction(&registeredBenchmarkCLI, addresses["ghostty_benchmark_cli"])
	registerFunction(&registeredCLITryAction, addresses["ghostty_cli_try_action"])
	registerFunction(&registeredConfigClone, addresses["ghostty_config_clone"])
	registerFunction(&registeredConfigDiagnosticsCount, addresses["ghostty_config_diagnostics_count"])
	registerFunction(&registeredConfigFinalize, addresses["ghostty_config_finalize"])
	registerFunction(&registeredConfigFree, addresses["ghostty_config_free"])
	registerFunction(&registeredConfigGet, addresses["ghostty_config_get"])
	registerFunction(&registeredConfigGetDiagnostic, addresses["ghostty_config_get_diagnostic"])
	registerFunction(&registeredConfigKeyIsBinding, addresses["ghostty_config_key_is_binding"])
	registerFunction(&registeredConfigLoadCLIArgs, addresses["ghostty_config_load_cli_args"])
	registerFunction(&registeredConfigLoadDefaultFiles, addresses["ghostty_config_load_default_files"])
	registerFunction(&registeredConfigLoadFile, addresses["ghostty_config_load_file"])
	registerFunction(&registeredConfigLoadRecursiveFiles, addresses["ghostty_config_load_recursive_files"])
	registerFunction(&registeredConfigNew, addresses["ghostty_config_new"])
	registerFunction(&registeredConfigOpenPath, addresses["ghostty_config_open_path"])
	registerFunction(&registeredConfigTrigger, addresses["ghostty_config_trigger"])
	registerFunction(&registeredInfoValue, addresses["ghostty_info"])
	registerFunction(&registeredInit, addresses["ghostty_init"])
	registerFunction(&registeredInspectorFree, addresses["ghostty_inspector_free"])
	registerFunction(&registeredInspectorKey, addresses["ghostty_inspector_key"])
	registerFunction(&registeredInspectorMouseButton, addresses["ghostty_inspector_mouse_button"])
	registerFunction(&registeredInspectorMousePos, addresses["ghostty_inspector_mouse_pos"])
	registerFunction(&registeredInspectorMouseScroll, addresses["ghostty_inspector_mouse_scroll"])
	registerFunction(&registeredInspectorSetContentScale, addresses["ghostty_inspector_set_content_scale"])
	registerFunction(&registeredInspectorSetFocus, addresses["ghostty_inspector_set_focus"])
	registerFunction(&registeredInspectorSetSize, addresses["ghostty_inspector_set_size"])
	registerFunction(&registeredInspectorText, addresses["ghostty_inspector_text"])
	registerFunction(&registeredSetWindowBackgroundBlur, addresses["ghostty_set_window_background_blur"])
	registerFunction(&registeredStringFree, addresses["ghostty_string_free"])
	registerFunction(&registeredSurfaceApp, addresses["ghostty_surface_app"])
	registerFunction(&registeredSurfaceBindingAction, addresses["ghostty_surface_binding_action"])
	registerFunction(&registeredSurfaceCompleteClipboardRequest, addresses["ghostty_surface_complete_clipboard_request"])
	registerFunction(&registeredSurfaceConfigNew, addresses["ghostty_surface_config_new"])
	registerFunction(&registeredSurfaceDraw, addresses["ghostty_surface_draw"])
	registerFunction(&registeredSurfaceForegroundPid, addresses["ghostty_surface_foreground_pid"])
	registerFunction(&registeredSurfaceFree, addresses["ghostty_surface_free"])
	registerFunction(&registeredSurfaceFreeText, addresses["ghostty_surface_free_text"])
	registerFunction(&registeredSurfaceHasSelection, addresses["ghostty_surface_has_selection"])
	registerFunction(&registeredSurfaceIMEPoint, addresses["ghostty_surface_ime_point"])
	registerFunction(&registeredSurfaceInheritedConfig, addresses["ghostty_surface_inherited_config"])
	registerFunction(&registeredSurfaceInspector, addresses["ghostty_surface_inspector"])
	registerFunction(&registeredSurfaceKey, addresses["ghostty_surface_key"])
	registerFunction(&registeredSurfaceKeyIsBinding, addresses["ghostty_surface_key_is_binding"])
	registerFunction(&registeredSurfaceKeyTranslationMods, addresses["ghostty_surface_key_translation_mods"])
	registerFunction(&registeredSurfaceMouseButton, addresses["ghostty_surface_mouse_button"])
	registerFunction(&registeredSurfaceMouseCaptured, addresses["ghostty_surface_mouse_captured"])
	registerFunction(&registeredSurfaceMousePos, addresses["ghostty_surface_mouse_pos"])
	registerFunction(&registeredSurfaceMousePressure, addresses["ghostty_surface_mouse_pressure"])
	registerFunction(&registeredSurfaceMouseScroll, addresses["ghostty_surface_mouse_scroll"])
	registerFunction(&registeredSurfaceNeedsConfirmQuit, addresses["ghostty_surface_needs_confirm_quit"])
	registerFunction(&registeredSurfaceNew, addresses["ghostty_surface_new"])
	registerFunction(&registeredSurfacePreedit, addresses["ghostty_surface_preedit"])
	registerFunction(&registeredSurfaceProcessExited, addresses["ghostty_surface_process_exited"])
	registerFunction(&registeredSurfaceReadSelection, addresses["ghostty_surface_read_selection"])
	registerFunction(&registeredSurfaceReadText, addresses["ghostty_surface_read_text"])
	registerFunction(&registeredSurfaceRefresh, addresses["ghostty_surface_refresh"])
	registerFunction(&registeredSurfaceRequestClose, addresses["ghostty_surface_request_close"])
	registerFunction(&registeredSurfaceSetColorScheme, addresses["ghostty_surface_set_color_scheme"])
	registerFunction(&registeredSurfaceSetContentScale, addresses["ghostty_surface_set_content_scale"])
	registerFunction(&registeredSurfaceSetFocus, addresses["ghostty_surface_set_focus"])
	registerFunction(&registeredSurfaceSetOcclusion, addresses["ghostty_surface_set_occlusion"])
	registerFunction(&registeredSurfaceSetSize, addresses["ghostty_surface_set_size"])
	registerFunction(&registeredSurfaceSizeValue, addresses["ghostty_surface_size"])
	registerFunction(&registeredSurfaceSplit, addresses["ghostty_surface_split"])
	registerFunction(&registeredSurfaceSplitEqualize, addresses["ghostty_surface_split_equalize"])
	registerFunction(&registeredSurfaceSplitFocus, addresses["ghostty_surface_split_focus"])
	registerFunction(&registeredSurfaceSplitResize, addresses["ghostty_surface_split_resize"])
	registerFunction(&registeredSurfaceText, addresses["ghostty_surface_text"])
	registerFunction(&registeredSurfaceTTYName, addresses["ghostty_surface_tty_name"])
	registerFunction(&registeredSurfaceUpdateConfig, addresses["ghostty_surface_update_config"])
	registerFunction(&registeredSurfaceUserdata, addresses["ghostty_surface_userdata"])
	registerFunction(&registeredTranslate, addresses["ghostty_translate"])

	AppFree = registeredAppFree
	AppHasGlobalKeybinds = registeredAppHasGlobalKeybinds
	AppKey = registeredAppKey
	AppKeyboardChanged = registeredAppKeyboardChanged
	AppNeedsConfirmQuit = registeredAppNeedsConfirmQuit
	AppNew = registeredAppNew
	AppOpenConfig = registeredAppOpenConfig
	AppSetColorScheme = registeredAppSetColorScheme
	AppSetFocus = registeredAppSetFocus
	AppTick = registeredAppTick
	AppUpdateConfig = registeredAppUpdateConfig
	AppUserdata = registeredAppUserdata
	BenchmarkCLI = registeredBenchmarkCLI
	CLITryAction = registeredCLITryAction
	ConfigClone = registeredConfigClone
	ConfigDiagnosticsCount = registeredConfigDiagnosticsCount
	ConfigFinalize = registeredConfigFinalize
	ConfigFree = registeredConfigFree
	ConfigGet = registeredConfigGet
	ConfigGetDiagnostic = registeredConfigGetDiagnostic
	ConfigKeyIsBinding = registeredConfigKeyIsBinding
	ConfigLoadCLIArgs = registeredConfigLoadCLIArgs
	ConfigLoadDefaultFiles = registeredConfigLoadDefaultFiles
	ConfigLoadFile = registeredConfigLoadFile
	ConfigLoadRecursiveFiles = registeredConfigLoadRecursiveFiles
	ConfigNew = registeredConfigNew
	ConfigOpenPath = registeredConfigOpenPath
	ConfigTrigger = registeredConfigTrigger
	InfoValue = registeredInfoValue
	Init = registeredInit
	InspectorFree = registeredInspectorFree
	InspectorKey = registeredInspectorKey
	InspectorMouseButton = registeredInspectorMouseButton
	InspectorMousePos = registeredInspectorMousePos
	InspectorMouseScroll = registeredInspectorMouseScroll
	InspectorSetContentScale = registeredInspectorSetContentScale
	InspectorSetFocus = registeredInspectorSetFocus
	InspectorSetSize = registeredInspectorSetSize
	InspectorText = registeredInspectorText
	SetWindowBackgroundBlur = registeredSetWindowBackgroundBlur
	StringFree = registeredStringFree
	SurfaceApp = registeredSurfaceApp
	SurfaceBindingAction = registeredSurfaceBindingAction
	SurfaceCompleteClipboardRequest = registeredSurfaceCompleteClipboardRequest
	SurfaceConfigNew = registeredSurfaceConfigNew
	SurfaceDraw = registeredSurfaceDraw
	SurfaceForegroundPid = registeredSurfaceForegroundPid
	SurfaceFree = registeredSurfaceFree
	SurfaceFreeText = registeredSurfaceFreeText
	SurfaceHasSelection = registeredSurfaceHasSelection
	SurfaceIMEPoint = registeredSurfaceIMEPoint
	SurfaceInheritedConfig = registeredSurfaceInheritedConfig
	SurfaceInspector = registeredSurfaceInspector
	SurfaceKey = registeredSurfaceKey
	SurfaceKeyIsBinding = registeredSurfaceKeyIsBinding
	SurfaceKeyTranslationMods = registeredSurfaceKeyTranslationMods
	SurfaceMouseButton = registeredSurfaceMouseButton
	SurfaceMouseCaptured = registeredSurfaceMouseCaptured
	SurfaceMousePos = registeredSurfaceMousePos
	SurfaceMousePressure = registeredSurfaceMousePressure
	SurfaceMouseScroll = registeredSurfaceMouseScroll
	SurfaceNeedsConfirmQuit = registeredSurfaceNeedsConfirmQuit
	SurfaceNew = registeredSurfaceNew
	SurfacePreedit = registeredSurfacePreedit
	SurfaceProcessExited = registeredSurfaceProcessExited
	SurfaceReadSelection = registeredSurfaceReadSelection
	SurfaceReadText = registeredSurfaceReadText
	SurfaceRefresh = registeredSurfaceRefresh
	SurfaceRequestClose = registeredSurfaceRequestClose
	SurfaceSetColorScheme = registeredSurfaceSetColorScheme
	SurfaceSetContentScale = registeredSurfaceSetContentScale
	SurfaceSetFocus = registeredSurfaceSetFocus
	SurfaceSetOcclusion = registeredSurfaceSetOcclusion
	SurfaceSetSize = registeredSurfaceSetSize
	SurfaceSizeValue = registeredSurfaceSizeValue
	SurfaceSplit = registeredSurfaceSplit
	SurfaceSplitEqualize = registeredSurfaceSplitEqualize
	SurfaceSplitFocus = registeredSurfaceSplitFocus
	SurfaceSplitResize = registeredSurfaceSplitResize
	SurfaceText = registeredSurfaceText
	SurfaceTTYName = registeredSurfaceTTYName
	SurfaceUpdateConfig = registeredSurfaceUpdateConfig
	SurfaceUserdata = registeredSurfaceUserdata
	Translate = registeredTranslate
	return nil
}
