// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import (
	"fmt"
	"github.com/bnema/purego"
)

var allSymbols = []string{
	"ghostty_app_free",
	"ghostty_app_has_global_keybinds",
	"ghostty_app_key",
	"ghostty_app_keyboard_changed",
	"ghostty_app_needs_confirm_quit",
	"ghostty_app_new",
	"ghostty_app_open_config",
	"ghostty_app_set_color_scheme",
	"ghostty_app_set_focus",
	"ghostty_app_tick",
	"ghostty_app_update_config",
	"ghostty_app_userdata",
	"ghostty_benchmark_cli",
	"ghostty_cli_try_action",
	"ghostty_config_clone",
	"ghostty_config_diagnostics_count",
	"ghostty_config_finalize",
	"ghostty_config_free",
	"ghostty_config_get",
	"ghostty_config_get_diagnostic",
	"ghostty_config_key_is_binding",
	"ghostty_config_load_cli_args",
	"ghostty_config_load_default_files",
	"ghostty_config_load_file",
	"ghostty_config_load_recursive_files",
	"ghostty_config_new",
	"ghostty_config_open_path",
	"ghostty_config_trigger",
	"ghostty_info",
	"ghostty_init",
	"ghostty_inspector_free",
	"ghostty_inspector_key",
	"ghostty_inspector_mouse_button",
	"ghostty_inspector_mouse_pos",
	"ghostty_inspector_mouse_scroll",
	"ghostty_inspector_set_content_scale",
	"ghostty_inspector_set_focus",
	"ghostty_inspector_set_size",
	"ghostty_inspector_text",
	"ghostty_set_window_background_blur",
	"ghostty_string_free",
	"ghostty_surface_app",
	"ghostty_surface_binding_action",
	"ghostty_surface_complete_clipboard_request",
	"ghostty_surface_config_new",
	"ghostty_surface_draw",
	"ghostty_surface_foreground_pid",
	"ghostty_surface_free",
	"ghostty_surface_free_text",
	"ghostty_surface_has_selection",
	"ghostty_surface_ime_point",
	"ghostty_surface_inherited_config",
	"ghostty_surface_inspector",
	"ghostty_surface_key",
	"ghostty_surface_key_is_binding",
	"ghostty_surface_key_translation_mods",
	"ghostty_surface_mouse_button",
	"ghostty_surface_mouse_captured",
	"ghostty_surface_mouse_pos",
	"ghostty_surface_mouse_pressure",
	"ghostty_surface_mouse_scroll",
	"ghostty_surface_needs_confirm_quit",
	"ghostty_surface_new",
	"ghostty_surface_preedit",
	"ghostty_surface_process_exited",
	"ghostty_surface_read_selection",
	"ghostty_surface_read_text",
	"ghostty_surface_refresh",
	"ghostty_surface_request_close",
	"ghostty_surface_set_color_scheme",
	"ghostty_surface_set_content_scale",
	"ghostty_surface_set_focus",
	"ghostty_surface_set_occlusion",
	"ghostty_surface_set_size",
	"ghostty_surface_size",
	"ghostty_surface_split",
	"ghostty_surface_split_equalize",
	"ghostty_surface_split_focus",
	"ghostty_surface_split_resize",
	"ghostty_surface_text",
	"ghostty_surface_tty_name",
	"ghostty_surface_update_config",
	"ghostty_surface_userdata",
	"ghostty_translate",
}

func register(handle uintptr) error {
	addresses := make(map[string]uintptr, len(allSymbols))
	for _, symbol := range allSymbols {
		address, err := purego.Dlsym(handle, symbol)
		if err != nil {
			return fmt.Errorf("resolve %s: %w", symbol, err)
		}
		addresses[symbol] = address
	}
	purego.RegisterFunc(&AppFree, addresses["ghostty_app_free"])
	purego.RegisterFunc(&AppHasGlobalKeybinds, addresses["ghostty_app_has_global_keybinds"])
	purego.RegisterFunc(&AppKey, addresses["ghostty_app_key"])
	purego.RegisterFunc(&AppKeyboardChanged, addresses["ghostty_app_keyboard_changed"])
	purego.RegisterFunc(&AppNeedsConfirmQuit, addresses["ghostty_app_needs_confirm_quit"])
	purego.RegisterFunc(&AppNew, addresses["ghostty_app_new"])
	purego.RegisterFunc(&AppOpenConfig, addresses["ghostty_app_open_config"])
	purego.RegisterFunc(&AppSetColorScheme, addresses["ghostty_app_set_color_scheme"])
	purego.RegisterFunc(&AppSetFocus, addresses["ghostty_app_set_focus"])
	purego.RegisterFunc(&AppTick, addresses["ghostty_app_tick"])
	purego.RegisterFunc(&AppUpdateConfig, addresses["ghostty_app_update_config"])
	purego.RegisterFunc(&AppUserdata, addresses["ghostty_app_userdata"])
	purego.RegisterFunc(&BenchmarkCLI, addresses["ghostty_benchmark_cli"])
	purego.RegisterFunc(&CLITryAction, addresses["ghostty_cli_try_action"])
	purego.RegisterFunc(&ConfigClone, addresses["ghostty_config_clone"])
	purego.RegisterFunc(&ConfigDiagnosticsCount, addresses["ghostty_config_diagnostics_count"])
	purego.RegisterFunc(&ConfigFinalize, addresses["ghostty_config_finalize"])
	purego.RegisterFunc(&ConfigFree, addresses["ghostty_config_free"])
	purego.RegisterFunc(&ConfigGet, addresses["ghostty_config_get"])
	purego.RegisterFunc(&ConfigGetDiagnostic, addresses["ghostty_config_get_diagnostic"])
	purego.RegisterFunc(&ConfigKeyIsBinding, addresses["ghostty_config_key_is_binding"])
	purego.RegisterFunc(&ConfigLoadCLIArgs, addresses["ghostty_config_load_cli_args"])
	purego.RegisterFunc(&ConfigLoadDefaultFiles, addresses["ghostty_config_load_default_files"])
	purego.RegisterFunc(&ConfigLoadFile, addresses["ghostty_config_load_file"])
	purego.RegisterFunc(&ConfigLoadRecursiveFiles, addresses["ghostty_config_load_recursive_files"])
	purego.RegisterFunc(&ConfigNew, addresses["ghostty_config_new"])
	purego.RegisterFunc(&ConfigOpenPath, addresses["ghostty_config_open_path"])
	purego.RegisterFunc(&ConfigTrigger, addresses["ghostty_config_trigger"])
	purego.RegisterFunc(&Info, addresses["ghostty_info"])
	purego.RegisterFunc(&Init, addresses["ghostty_init"])
	purego.RegisterFunc(&InspectorFree, addresses["ghostty_inspector_free"])
	purego.RegisterFunc(&InspectorKey, addresses["ghostty_inspector_key"])
	purego.RegisterFunc(&InspectorMouseButton, addresses["ghostty_inspector_mouse_button"])
	purego.RegisterFunc(&InspectorMousePos, addresses["ghostty_inspector_mouse_pos"])
	purego.RegisterFunc(&InspectorMouseScroll, addresses["ghostty_inspector_mouse_scroll"])
	purego.RegisterFunc(&InspectorSetContentScale, addresses["ghostty_inspector_set_content_scale"])
	purego.RegisterFunc(&InspectorSetFocus, addresses["ghostty_inspector_set_focus"])
	purego.RegisterFunc(&InspectorSetSize, addresses["ghostty_inspector_set_size"])
	purego.RegisterFunc(&InspectorText, addresses["ghostty_inspector_text"])
	purego.RegisterFunc(&SetWindowBackgroundBlur, addresses["ghostty_set_window_background_blur"])
	purego.RegisterFunc(&StringFree, addresses["ghostty_string_free"])
	purego.RegisterFunc(&SurfaceApp, addresses["ghostty_surface_app"])
	purego.RegisterFunc(&SurfaceBindingAction, addresses["ghostty_surface_binding_action"])
	purego.RegisterFunc(&SurfaceCompleteClipboardRequest, addresses["ghostty_surface_complete_clipboard_request"])
	purego.RegisterFunc(&SurfaceConfigNew, addresses["ghostty_surface_config_new"])
	purego.RegisterFunc(&SurfaceDraw, addresses["ghostty_surface_draw"])
	purego.RegisterFunc(&SurfaceForegroundPid, addresses["ghostty_surface_foreground_pid"])
	purego.RegisterFunc(&SurfaceFree, addresses["ghostty_surface_free"])
	purego.RegisterFunc(&SurfaceFreeText, addresses["ghostty_surface_free_text"])
	purego.RegisterFunc(&SurfaceHasSelection, addresses["ghostty_surface_has_selection"])
	purego.RegisterFunc(&SurfaceIMEPoint, addresses["ghostty_surface_ime_point"])
	purego.RegisterFunc(&SurfaceInheritedConfig, addresses["ghostty_surface_inherited_config"])
	purego.RegisterFunc(&SurfaceInspector, addresses["ghostty_surface_inspector"])
	purego.RegisterFunc(&SurfaceKey, addresses["ghostty_surface_key"])
	purego.RegisterFunc(&SurfaceKeyIsBinding, addresses["ghostty_surface_key_is_binding"])
	purego.RegisterFunc(&SurfaceKeyTranslationMods, addresses["ghostty_surface_key_translation_mods"])
	purego.RegisterFunc(&SurfaceMouseButton, addresses["ghostty_surface_mouse_button"])
	purego.RegisterFunc(&SurfaceMouseCaptured, addresses["ghostty_surface_mouse_captured"])
	purego.RegisterFunc(&SurfaceMousePos, addresses["ghostty_surface_mouse_pos"])
	purego.RegisterFunc(&SurfaceMousePressure, addresses["ghostty_surface_mouse_pressure"])
	purego.RegisterFunc(&SurfaceMouseScroll, addresses["ghostty_surface_mouse_scroll"])
	purego.RegisterFunc(&SurfaceNeedsConfirmQuit, addresses["ghostty_surface_needs_confirm_quit"])
	purego.RegisterFunc(&SurfaceNew, addresses["ghostty_surface_new"])
	purego.RegisterFunc(&SurfacePreedit, addresses["ghostty_surface_preedit"])
	purego.RegisterFunc(&SurfaceProcessExited, addresses["ghostty_surface_process_exited"])
	purego.RegisterFunc(&SurfaceReadSelection, addresses["ghostty_surface_read_selection"])
	purego.RegisterFunc(&SurfaceReadText, addresses["ghostty_surface_read_text"])
	purego.RegisterFunc(&SurfaceRefresh, addresses["ghostty_surface_refresh"])
	purego.RegisterFunc(&SurfaceRequestClose, addresses["ghostty_surface_request_close"])
	purego.RegisterFunc(&SurfaceSetColorScheme, addresses["ghostty_surface_set_color_scheme"])
	purego.RegisterFunc(&SurfaceSetContentScale, addresses["ghostty_surface_set_content_scale"])
	purego.RegisterFunc(&SurfaceSetFocus, addresses["ghostty_surface_set_focus"])
	purego.RegisterFunc(&SurfaceSetOcclusion, addresses["ghostty_surface_set_occlusion"])
	purego.RegisterFunc(&SurfaceSetSize, addresses["ghostty_surface_set_size"])
	purego.RegisterFunc(&SurfaceSize, addresses["ghostty_surface_size"])
	purego.RegisterFunc(&SurfaceSplit, addresses["ghostty_surface_split"])
	purego.RegisterFunc(&SurfaceSplitEqualize, addresses["ghostty_surface_split_equalize"])
	purego.RegisterFunc(&SurfaceSplitFocus, addresses["ghostty_surface_split_focus"])
	purego.RegisterFunc(&SurfaceSplitResize, addresses["ghostty_surface_split_resize"])
	purego.RegisterFunc(&SurfaceText, addresses["ghostty_surface_text"])
	purego.RegisterFunc(&SurfaceTTYName, addresses["ghostty_surface_tty_name"])
	purego.RegisterFunc(&SurfaceUpdateConfig, addresses["ghostty_surface_update_config"])
	purego.RegisterFunc(&SurfaceUserdata, addresses["ghostty_surface_userdata"])
	purego.RegisterFunc(&Translate, addresses["ghostty_translate"])
	return nil
}
