// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

//go:build amd64

package ghostty

type ActionMoveTabS struct {
	Amount int
}

type ActionSearchSelectedS struct {
	Selected int
}

type ActionSearchTotalS struct {
	Total int
}

type String struct {
	Ptr      *byte
	Len      uintptr
	Sentinel bool
	_        [7]byte
}
