// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

//go:build arm64

package ghostty

type ActionMoveTabS struct {
	Amount int32
}

type ActionSearchSelectedS struct {
	Selected int32
}

type ActionSearchTotalS struct {
	Total int32
}

type String struct {
	Ptr      *byte
	Len      uint32
	Sentinel bool
	_        [3]byte
}
