// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import "unsafe"

type ActionCellSizeS struct {
	Width  uint32
	Height uint32
}

type ActionCloseTabMode int32

type ActionColorChangeS struct {
	Kind ActionColorKind
	R    byte
	G    byte
	B    byte
	_    [1]byte
}

type ActionColorKind int32

type ActionCommandFinishedS struct {
	ExitCode int16
	_        [6]byte
	Duration uint64
}

type ActionConfigChangeS struct {
	Config ConfigHandle
}

type ActionDesktopNotificationS struct {
	Title *byte
	Body  *byte
}

type ActionFloatWindowE int32

type ActionFullscreen int32

type ActionGotoSplitE int32

type ActionGotoTabE int32

type ActionGotoWindowE int32

type ActionInitialSizeS struct {
	Width  uint32
	Height uint32
}

type ActionInspectorE int32

type ActionKeySequenceS struct {
	Active  bool
	_       [3]byte
	Trigger InputTrigger
}

type ActionKeyTableS struct {
	Tag   ActionKeyTableTag
	_     [4]byte
	Value ActionKeyTableU
}

type ActionKeyTableTag int32

type ActionKeyTableU struct {
	_ [0]uint64
	_ [16]byte
}

func (u *ActionKeyTableU) SetActivate(value ActionKeyTableActivate) {
	*(*ActionKeyTableActivate)(unsafe.Pointer(u)) = value
}

func (u ActionKeyTableU) Activate() ActionKeyTableActivate {
	return *(*ActionKeyTableActivate)(unsafe.Pointer(&u))
}

type ActionKeyTableActivate struct {
	Name *byte
	Len  uintptr
}

type ActionMouseOverLinkS struct {
	URL *byte
	Len uintptr
}

type ActionMouseShapeE int32

type ActionMouseVisibilityE int32

type ActionMoveTabS struct {
	Amount int
}

type ActionOpenURLKind int32

type ActionOpenURLS struct {
	Kind ActionOpenURLKind
	_    [4]byte
	URL  *byte
	Len  uintptr
}

type ActionProgressReportS struct {
	State    ActionProgressReportState
	Progress int8
	_        [3]byte
}

type ActionProgressReportState int32

type ActionPromptTitleE int32

type ActionPwdS struct {
	Pwd *byte
}

type ActionQuitTimerE int32

type ActionReadonlyE int32

type ActionReloadConfigS struct {
	Soft bool
}

type ActionRendererHealthE int32

type ActionResizeSplitDirection int32

type ActionResizeSplitS struct {
	Amount    uint16
	_         [2]byte
	Direction ActionResizeSplitDirection
}

type ActionS struct {
	Tag    ActionTag
	_      [4]byte
	Action ActionU
}

type ActionScrollbarS struct {
	Total  uint64
	Offset uint64
	Len    uint64
}

type ActionSearchSelectedS struct {
	Selected int
}

type ActionSearchTotalS struct {
	Total int
}

type ActionSecureInputE int32

type ActionSetTitleS struct {
	Title *byte
}

type ActionSizeLimitS struct {
	MinWidth  uint32
	MinHeight uint32
	MaxWidth  uint32
	MaxHeight uint32
}

type ActionSplitDirection int32

type ActionStartSearchS struct {
	Needle *byte
}

type ActionTag int32

type ActionU struct {
	_ [0]uint64
	_ [24]byte
}

func (u *ActionU) SetNewSplit(value ActionSplitDirection) {
	*(*ActionSplitDirection)(unsafe.Pointer(u)) = value
}

func (u ActionU) NewSplit() ActionSplitDirection {
	return *(*ActionSplitDirection)(unsafe.Pointer(&u))
}

func (u *ActionU) SetToggleFullscreen(value ActionFullscreen) {
	*(*ActionFullscreen)(unsafe.Pointer(u)) = value
}

func (u ActionU) ToggleFullscreen() ActionFullscreen {
	return *(*ActionFullscreen)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMoveTab(value ActionMoveTabS) {
	*(*ActionMoveTabS)(unsafe.Pointer(u)) = value
}

func (u ActionU) MoveTab() ActionMoveTabS {
	return *(*ActionMoveTabS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoTab(value ActionGotoTabE) {
	*(*ActionGotoTabE)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoTab() ActionGotoTabE {
	return *(*ActionGotoTabE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoSplit(value ActionGotoSplitE) {
	*(*ActionGotoSplitE)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoSplit() ActionGotoSplitE {
	return *(*ActionGotoSplitE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoWindow(value ActionGotoWindowE) {
	*(*ActionGotoWindowE)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoWindow() ActionGotoWindowE {
	return *(*ActionGotoWindowE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetResizeSplit(value ActionResizeSplitS) {
	*(*ActionResizeSplitS)(unsafe.Pointer(u)) = value
}

func (u ActionU) ResizeSplit() ActionResizeSplitS {
	return *(*ActionResizeSplitS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSizeLimit(value ActionSizeLimitS) {
	*(*ActionSizeLimitS)(unsafe.Pointer(u)) = value
}

func (u ActionU) SizeLimit() ActionSizeLimitS {
	return *(*ActionSizeLimitS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetInitialSize(value ActionInitialSizeS) {
	*(*ActionInitialSizeS)(unsafe.Pointer(u)) = value
}

func (u ActionU) InitialSize() ActionInitialSizeS {
	return *(*ActionInitialSizeS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCellSize(value ActionCellSizeS) {
	*(*ActionCellSizeS)(unsafe.Pointer(u)) = value
}

func (u ActionU) CellSize() ActionCellSizeS {
	return *(*ActionCellSizeS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetScrollbar(value ActionScrollbarS) {
	*(*ActionScrollbarS)(unsafe.Pointer(u)) = value
}

func (u ActionU) Scrollbar() ActionScrollbarS {
	return *(*ActionScrollbarS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetInspector(value ActionInspectorE) {
	*(*ActionInspectorE)(unsafe.Pointer(u)) = value
}

func (u ActionU) Inspector() ActionInspectorE {
	return *(*ActionInspectorE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetDesktopNotification(value ActionDesktopNotificationS) {
	*(*ActionDesktopNotificationS)(unsafe.Pointer(u)) = value
}

func (u ActionU) DesktopNotification() ActionDesktopNotificationS {
	return *(*ActionDesktopNotificationS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSetTitle(value ActionSetTitleS) {
	*(*ActionSetTitleS)(unsafe.Pointer(u)) = value
}

func (u ActionU) SetTitle() ActionSetTitleS {
	return *(*ActionSetTitleS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSetTabTitle(value ActionSetTitleS) {
	*(*ActionSetTitleS)(unsafe.Pointer(u)) = value
}

func (u ActionU) SetTabTitle() ActionSetTitleS {
	return *(*ActionSetTitleS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetPromptTitle(value ActionPromptTitleE) {
	*(*ActionPromptTitleE)(unsafe.Pointer(u)) = value
}

func (u ActionU) PromptTitle() ActionPromptTitleE {
	return *(*ActionPromptTitleE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetPwd(value ActionPwdS) {
	*(*ActionPwdS)(unsafe.Pointer(u)) = value
}

func (u ActionU) Pwd() ActionPwdS {
	return *(*ActionPwdS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseShape(value ActionMouseShapeE) {
	*(*ActionMouseShapeE)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseShape() ActionMouseShapeE {
	return *(*ActionMouseShapeE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseVisibility(value ActionMouseVisibilityE) {
	*(*ActionMouseVisibilityE)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseVisibility() ActionMouseVisibilityE {
	return *(*ActionMouseVisibilityE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseOverLink(value ActionMouseOverLinkS) {
	*(*ActionMouseOverLinkS)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseOverLink() ActionMouseOverLinkS {
	return *(*ActionMouseOverLinkS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetRendererHealth(value ActionRendererHealthE) {
	*(*ActionRendererHealthE)(unsafe.Pointer(u)) = value
}

func (u ActionU) RendererHealth() ActionRendererHealthE {
	return *(*ActionRendererHealthE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetQuitTimer(value ActionQuitTimerE) {
	*(*ActionQuitTimerE)(unsafe.Pointer(u)) = value
}

func (u ActionU) QuitTimer() ActionQuitTimerE {
	return *(*ActionQuitTimerE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetFloatWindow(value ActionFloatWindowE) {
	*(*ActionFloatWindowE)(unsafe.Pointer(u)) = value
}

func (u ActionU) FloatWindow() ActionFloatWindowE {
	return *(*ActionFloatWindowE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSecureInput(value ActionSecureInputE) {
	*(*ActionSecureInputE)(unsafe.Pointer(u)) = value
}

func (u ActionU) SecureInput() ActionSecureInputE {
	return *(*ActionSecureInputE)(unsafe.Pointer(&u))
}

func (u *ActionU) SetKeySequence(value ActionKeySequenceS) {
	*(*ActionKeySequenceS)(unsafe.Pointer(u)) = value
}

func (u ActionU) KeySequence() ActionKeySequenceS {
	return *(*ActionKeySequenceS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetKeyTable(value ActionKeyTableS) {
	*(*ActionKeyTableS)(unsafe.Pointer(u)) = value
}

func (u ActionU) KeyTable() ActionKeyTableS {
	return *(*ActionKeyTableS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetColorChange(value ActionColorChangeS) {
	*(*ActionColorChangeS)(unsafe.Pointer(u)) = value
}

func (u ActionU) ColorChange() ActionColorChangeS {
	return *(*ActionColorChangeS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetReloadConfig(value ActionReloadConfigS) {
	*(*ActionReloadConfigS)(unsafe.Pointer(u)) = value
}

func (u ActionU) ReloadConfig() ActionReloadConfigS {
	return *(*ActionReloadConfigS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetConfigChange(value ActionConfigChangeS) {
	*(*ActionConfigChangeS)(unsafe.Pointer(u)) = value
}

func (u ActionU) ConfigChange() ActionConfigChangeS {
	return *(*ActionConfigChangeS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetOpenURL(value ActionOpenURLS) {
	*(*ActionOpenURLS)(unsafe.Pointer(u)) = value
}

func (u ActionU) OpenURL() ActionOpenURLS {
	return *(*ActionOpenURLS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCloseTabMode(value ActionCloseTabMode) {
	*(*ActionCloseTabMode)(unsafe.Pointer(u)) = value
}

func (u ActionU) CloseTabMode() ActionCloseTabMode {
	return *(*ActionCloseTabMode)(unsafe.Pointer(&u))
}

func (u *ActionU) SetChildExited(value SurfaceMessageChildexited) {
	*(*SurfaceMessageChildexited)(unsafe.Pointer(u)) = value
}

func (u ActionU) ChildExited() SurfaceMessageChildexited {
	return *(*SurfaceMessageChildexited)(unsafe.Pointer(&u))
}

func (u *ActionU) SetProgressReport(value ActionProgressReportS) {
	*(*ActionProgressReportS)(unsafe.Pointer(u)) = value
}

func (u ActionU) ProgressReport() ActionProgressReportS {
	return *(*ActionProgressReportS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCommandFinished(value ActionCommandFinishedS) {
	*(*ActionCommandFinishedS)(unsafe.Pointer(u)) = value
}

func (u ActionU) CommandFinished() ActionCommandFinishedS {
	return *(*ActionCommandFinishedS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetStartSearch(value ActionStartSearchS) {
	*(*ActionStartSearchS)(unsafe.Pointer(u)) = value
}

func (u ActionU) StartSearch() ActionStartSearchS {
	return *(*ActionStartSearchS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSearchTotal(value ActionSearchTotalS) {
	*(*ActionSearchTotalS)(unsafe.Pointer(u)) = value
}

func (u ActionU) SearchTotal() ActionSearchTotalS {
	return *(*ActionSearchTotalS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSearchSelected(value ActionSearchSelectedS) {
	*(*ActionSearchSelectedS)(unsafe.Pointer(u)) = value
}

func (u ActionU) SearchSelected() ActionSearchSelectedS {
	return *(*ActionSearchSelectedS)(unsafe.Pointer(&u))
}

func (u *ActionU) SetReadonly(value ActionReadonlyE) {
	*(*ActionReadonlyE)(unsafe.Pointer(u)) = value
}

func (u ActionU) Readonly() ActionReadonlyE {
	return *(*ActionReadonlyE)(unsafe.Pointer(&u))
}

type AppHandle uintptr

type BindingFlags int32

type BuildMode int32

type ClipboardContent struct {
	Mime *byte
	Data *byte
}

type Clipboard int32

type ClipboardRequest int32

type ColorScheme int32

type ConfigHandle uintptr

type Diagnostic struct {
	Message *byte
}

type EnvVar struct {
	Key   *byte
	Value *byte
}

type InfoS struct {
	BuildMode  BuildMode
	_          [4]byte
	Version    *byte
	VersionLen uintptr
}

type InputAction int32

type InputKeyE int32

type InputKeyS struct {
	Action             InputAction
	Mods               InputMods
	ConsumedMods       InputMods
	Keycode            uint32
	Text               *byte
	UnshiftedCodepoint uint32
	Composing          bool
	_                  [3]byte
}

type InputMods int32

type InputMouseButton int32

type InputMouseState int32

type InputScrollMods int32

type InputTriggerKey struct {
	_ [0]uint32
	_ [4]byte
}

func (u *InputTriggerKey) SetPhysical(value InputKeyE) {
	*(*InputKeyE)(unsafe.Pointer(u)) = value
}

func (u InputTriggerKey) Physical() InputKeyE {
	return *(*InputKeyE)(unsafe.Pointer(&u))
}

func (u *InputTriggerKey) SetUnicode(value uint32) {
	*(*uint32)(unsafe.Pointer(u)) = value
}

func (u InputTriggerKey) Unicode() uint32 {
	return *(*uint32)(unsafe.Pointer(&u))
}

type InputTrigger struct {
	Tag  InputTriggerTag
	Key  InputTriggerKey
	Mods InputMods
}

type InputTriggerTag int32

type InspectorHandle uintptr

type IPCActionNewWindow struct {
	Arguments **byte
}

type IPCAction struct {
	_ [0]uint64
	_ [8]byte
}

func (u *IPCAction) SetNewWindow(value IPCActionNewWindow) {
	*(*IPCActionNewWindow)(unsafe.Pointer(u)) = value
}

func (u IPCAction) NewWindow() IPCActionNewWindow {
	return *(*IPCActionNewWindow)(unsafe.Pointer(&u))
}

type IPCTarget struct {
	_ [0]uint64
	_ [8]byte
}

func (u *IPCTarget) SetKlass(value *byte) {
	*(**byte)(unsafe.Pointer(u)) = value
}

func (u IPCTarget) Klass() *byte {
	return *(**byte)(unsafe.Pointer(&u))
}

type PlatformE int32

type PlatformIosS struct {
	Uiview unsafe.Pointer
}

type PlatformMacosS struct {
	Nsview unsafe.Pointer
}

type PlatformU struct {
	_ [0]uint64
	_ [8]byte
}

func (u *PlatformU) SetMacos(value PlatformMacosS) {
	*(*PlatformMacosS)(unsafe.Pointer(u)) = value
}

func (u PlatformU) Macos() PlatformMacosS {
	return *(*PlatformMacosS)(unsafe.Pointer(&u))
}

func (u *PlatformU) SetIos(value PlatformIosS) {
	*(*PlatformIosS)(unsafe.Pointer(u)) = value
}

func (u PlatformU) Ios() PlatformIosS {
	return *(*PlatformIosS)(unsafe.Pointer(&u))
}

type PointCoord int32

type Point struct {
	Tag   PointTag
	Coord PointCoord
	X     uint32
	Y     uint32
}

type PointTag int32

type QuickTerminalSizeValue struct {
	_ [0]uint32
	_ [4]byte
}

func (u *QuickTerminalSizeValue) SetPercentage(value float32) {
	*(*float32)(unsafe.Pointer(u)) = value
}

func (u QuickTerminalSizeValue) Percentage() float32 {
	return *(*float32)(unsafe.Pointer(&u))
}

func (u *QuickTerminalSizeValue) SetPixels(value uint32) {
	*(*uint32)(unsafe.Pointer(u)) = value
}

func (u QuickTerminalSizeValue) Pixels() uint32 {
	return *(*uint32)(unsafe.Pointer(&u))
}

type RuntimeActionCb uintptr

type RuntimeCloseSurfaceCb uintptr

type RuntimeConfig struct {
	Userdata                   unsafe.Pointer
	SupportsSelectionClipboard bool
	_                          [7]byte
	WakeupCb                   uintptr
	ActionCb                   uintptr
	ReadClipboardCb            uintptr
	ConfirmReadClipboardCb     uintptr
	WriteClipboardCb           uintptr
	CloseSurfaceCb             uintptr
}

type RuntimeConfirmReadClipboardCb uintptr

type RuntimeReadClipboardCb uintptr

type RuntimeWakeupCb uintptr

type RuntimeWriteClipboardCb uintptr

type Selection struct {
	TopLeft     Point
	BottomRight Point
	Rectangle   bool
	_           [3]byte
}

type String struct {
	Ptr      *byte
	Len      uintptr
	Sentinel bool
	_        [7]byte
}

type SurfaceConfig struct {
	PlatformTag      PlatformE
	_                [4]byte
	Platform         PlatformU
	Userdata         unsafe.Pointer
	ScaleFactor      float64
	FontSize         float32
	_                [4]byte
	WorkingDirectory *byte
	Command          *byte
	EnvVars          *EnvVar
	EnvVarCount      uintptr
	InitialInput     *byte
	WaitAfterCommand bool
	_                [3]byte
	Context          SurfaceContext
}

type SurfaceContext int32

type SurfaceMessageChildexited struct {
	ExitCode   uint32
	_          [4]byte
	TimetimeMs uint64
}

type SurfaceSizeS struct {
	Columns      uint16
	Rows         uint16
	WidthPx      uint32
	HeightPx     uint32
	CellWidthPx  uint32
	CellHeightPx uint32
}

type SurfaceHandle uintptr

type TargetS struct {
	Tag    TargetTag
	_      [4]byte
	Target TargetU
}

type TargetTag int32

type TargetU struct {
	_ [0]uint64
	_ [8]byte
}

func (u *TargetU) SetSurface(value SurfaceHandle) {
	*(*SurfaceHandle)(unsafe.Pointer(u)) = value
}

func (u TargetU) Surface() SurfaceHandle {
	return *(*SurfaceHandle)(unsafe.Pointer(&u))
}

type Text struct {
	TlPxX       float64
	TlPxY       float64
	OffsetStart uint32
	OffsetLen   uint32
	Text        *byte
	TextLen     uintptr
}
