// Code generated by ghosttygen; DO NOT EDIT.
// Ghostty commit: 4d605bf0d819df901a0332bbb320dc849fdd82e4

package ghostty

import "unsafe"

type ActionCellSize struct {
	Width  uint32
	Height uint32
}

type ActionCloseTabMode int32

type ActionColorChange struct {
	Kind ActionColorKind
	R    byte
	G    byte
	B    byte
	_    [1]byte
}

type ActionColorKind int32

type ActionCommandFinished struct {
	ExitCode int16
	_        [6]byte
	Duration uint64
}

type ActionConfigChange struct {
	Config ConfigHandle
}

type ActionDesktopNotification struct {
	Title *byte
	Body  *byte
}

type ActionFloatWindow int32

type ActionFullscreen int32

type ActionGotoSplit int32

type ActionGotoTab int32

type ActionGotoWindow int32

type ActionInitialSize struct {
	Width  uint32
	Height uint32
}

type ActionInspector int32

type ActionKeySequence struct {
	Active  bool
	_       [3]byte
	Trigger InputTrigger
}

type ActionKeyTable struct {
	Tag   ActionKeyTableTag
	_     [4]byte
	Value ActionKeyTableU
}

type ActionKeyTableTag int32

type ActionKeyTableU struct {
	_ [0]uint64
	_ [16]byte
}

func (u *ActionKeyTableU) SetActivate(value ActionKeyTableActivate) {
	*(*ActionKeyTableActivate)(unsafe.Pointer(u)) = value
}

func (u ActionKeyTableU) Activate() ActionKeyTableActivate {
	return *(*ActionKeyTableActivate)(unsafe.Pointer(&u))
}

type ActionKeyTableActivate struct {
	Name *byte
	Len  uintptr
}

type ActionMouseOverLink struct {
	URL *byte
	Len uintptr
}

type ActionMouseShape int32

type ActionMouseVisibility int32

type ActionMoveTab struct {
	Amount int
}

type ActionOpenURLKind int32

type ActionOpenURL struct {
	Kind ActionOpenURLKind
	_    [4]byte
	URL  *byte
	Len  uintptr
}

type ActionProgressReport struct {
	State    ActionProgressReportState
	Progress int8
	_        [3]byte
}

type ActionProgressReportState int32

type ActionPromptTitle int32

type ActionPwd struct {
	Pwd *byte
}

type ActionQuitTimer int32

type ActionReadonly int32

type ActionReloadConfig struct {
	Soft bool
}

type ActionRendererHealth int32

type ActionResizeSplitDirection int32

type ActionResizeSplit struct {
	Amount    uint16
	_         [2]byte
	Direction ActionResizeSplitDirection
}

type Action struct {
	Tag    ActionTag
	_      [4]byte
	Action ActionU
}

type ActionScrollbar struct {
	Total  uint64
	Offset uint64
	Len    uint64
}

type ActionSearchSelected struct {
	Selected int
}

type ActionSearchTotal struct {
	Total int
}

type ActionSecureInput int32

type ActionSetTitle struct {
	Title *byte
}

type ActionSizeLimit struct {
	MinWidth  uint32
	MinHeight uint32
	MaxWidth  uint32
	MaxHeight uint32
}

type ActionSplitDirection int32

type ActionStartSearch struct {
	Needle *byte
}

type ActionTag int32

type ActionU struct {
	_ [0]uint64
	_ [24]byte
}

func (u *ActionU) SetNewSplit(value ActionSplitDirection) {
	*(*ActionSplitDirection)(unsafe.Pointer(u)) = value
}

func (u ActionU) NewSplit() ActionSplitDirection {
	return *(*ActionSplitDirection)(unsafe.Pointer(&u))
}

func (u *ActionU) SetToggleFullscreen(value ActionFullscreen) {
	*(*ActionFullscreen)(unsafe.Pointer(u)) = value
}

func (u ActionU) ToggleFullscreen() ActionFullscreen {
	return *(*ActionFullscreen)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMoveTab(value ActionMoveTab) {
	*(*ActionMoveTab)(unsafe.Pointer(u)) = value
}

func (u ActionU) MoveTab() ActionMoveTab {
	return *(*ActionMoveTab)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoTab(value ActionGotoTab) {
	*(*ActionGotoTab)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoTab() ActionGotoTab {
	return *(*ActionGotoTab)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoSplit(value ActionGotoSplit) {
	*(*ActionGotoSplit)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoSplit() ActionGotoSplit {
	return *(*ActionGotoSplit)(unsafe.Pointer(&u))
}

func (u *ActionU) SetGotoWindow(value ActionGotoWindow) {
	*(*ActionGotoWindow)(unsafe.Pointer(u)) = value
}

func (u ActionU) GotoWindow() ActionGotoWindow {
	return *(*ActionGotoWindow)(unsafe.Pointer(&u))
}

func (u *ActionU) SetResizeSplit(value ActionResizeSplit) {
	*(*ActionResizeSplit)(unsafe.Pointer(u)) = value
}

func (u ActionU) ResizeSplit() ActionResizeSplit {
	return *(*ActionResizeSplit)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSizeLimit(value ActionSizeLimit) {
	*(*ActionSizeLimit)(unsafe.Pointer(u)) = value
}

func (u ActionU) SizeLimit() ActionSizeLimit {
	return *(*ActionSizeLimit)(unsafe.Pointer(&u))
}

func (u *ActionU) SetInitialSize(value ActionInitialSize) {
	*(*ActionInitialSize)(unsafe.Pointer(u)) = value
}

func (u ActionU) InitialSize() ActionInitialSize {
	return *(*ActionInitialSize)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCellSize(value ActionCellSize) {
	*(*ActionCellSize)(unsafe.Pointer(u)) = value
}

func (u ActionU) CellSize() ActionCellSize {
	return *(*ActionCellSize)(unsafe.Pointer(&u))
}

func (u *ActionU) SetScrollbar(value ActionScrollbar) {
	*(*ActionScrollbar)(unsafe.Pointer(u)) = value
}

func (u ActionU) Scrollbar() ActionScrollbar {
	return *(*ActionScrollbar)(unsafe.Pointer(&u))
}

func (u *ActionU) SetInspector(value ActionInspector) {
	*(*ActionInspector)(unsafe.Pointer(u)) = value
}

func (u ActionU) Inspector() ActionInspector {
	return *(*ActionInspector)(unsafe.Pointer(&u))
}

func (u *ActionU) SetDesktopNotification(value ActionDesktopNotification) {
	*(*ActionDesktopNotification)(unsafe.Pointer(u)) = value
}

func (u ActionU) DesktopNotification() ActionDesktopNotification {
	return *(*ActionDesktopNotification)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSetTitle(value ActionSetTitle) {
	*(*ActionSetTitle)(unsafe.Pointer(u)) = value
}

func (u ActionU) SetTitle() ActionSetTitle {
	return *(*ActionSetTitle)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSetTabTitle(value ActionSetTitle) {
	*(*ActionSetTitle)(unsafe.Pointer(u)) = value
}

func (u ActionU) SetTabTitle() ActionSetTitle {
	return *(*ActionSetTitle)(unsafe.Pointer(&u))
}

func (u *ActionU) SetPromptTitle(value ActionPromptTitle) {
	*(*ActionPromptTitle)(unsafe.Pointer(u)) = value
}

func (u ActionU) PromptTitle() ActionPromptTitle {
	return *(*ActionPromptTitle)(unsafe.Pointer(&u))
}

func (u *ActionU) SetPwd(value ActionPwd) {
	*(*ActionPwd)(unsafe.Pointer(u)) = value
}

func (u ActionU) Pwd() ActionPwd {
	return *(*ActionPwd)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseShape(value ActionMouseShape) {
	*(*ActionMouseShape)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseShape() ActionMouseShape {
	return *(*ActionMouseShape)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseVisibility(value ActionMouseVisibility) {
	*(*ActionMouseVisibility)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseVisibility() ActionMouseVisibility {
	return *(*ActionMouseVisibility)(unsafe.Pointer(&u))
}

func (u *ActionU) SetMouseOverLink(value ActionMouseOverLink) {
	*(*ActionMouseOverLink)(unsafe.Pointer(u)) = value
}

func (u ActionU) MouseOverLink() ActionMouseOverLink {
	return *(*ActionMouseOverLink)(unsafe.Pointer(&u))
}

func (u *ActionU) SetRendererHealth(value ActionRendererHealth) {
	*(*ActionRendererHealth)(unsafe.Pointer(u)) = value
}

func (u ActionU) RendererHealth() ActionRendererHealth {
	return *(*ActionRendererHealth)(unsafe.Pointer(&u))
}

func (u *ActionU) SetQuitTimer(value ActionQuitTimer) {
	*(*ActionQuitTimer)(unsafe.Pointer(u)) = value
}

func (u ActionU) QuitTimer() ActionQuitTimer {
	return *(*ActionQuitTimer)(unsafe.Pointer(&u))
}

func (u *ActionU) SetFloatWindow(value ActionFloatWindow) {
	*(*ActionFloatWindow)(unsafe.Pointer(u)) = value
}

func (u ActionU) FloatWindow() ActionFloatWindow {
	return *(*ActionFloatWindow)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSecureInput(value ActionSecureInput) {
	*(*ActionSecureInput)(unsafe.Pointer(u)) = value
}

func (u ActionU) SecureInput() ActionSecureInput {
	return *(*ActionSecureInput)(unsafe.Pointer(&u))
}

func (u *ActionU) SetKeySequence(value ActionKeySequence) {
	*(*ActionKeySequence)(unsafe.Pointer(u)) = value
}

func (u ActionU) KeySequence() ActionKeySequence {
	return *(*ActionKeySequence)(unsafe.Pointer(&u))
}

func (u *ActionU) SetKeyTable(value ActionKeyTable) {
	*(*ActionKeyTable)(unsafe.Pointer(u)) = value
}

func (u ActionU) KeyTable() ActionKeyTable {
	return *(*ActionKeyTable)(unsafe.Pointer(&u))
}

func (u *ActionU) SetColorChange(value ActionColorChange) {
	*(*ActionColorChange)(unsafe.Pointer(u)) = value
}

func (u ActionU) ColorChange() ActionColorChange {
	return *(*ActionColorChange)(unsafe.Pointer(&u))
}

func (u *ActionU) SetReloadConfig(value ActionReloadConfig) {
	*(*ActionReloadConfig)(unsafe.Pointer(u)) = value
}

func (u ActionU) ReloadConfig() ActionReloadConfig {
	return *(*ActionReloadConfig)(unsafe.Pointer(&u))
}

func (u *ActionU) SetConfigChange(value ActionConfigChange) {
	*(*ActionConfigChange)(unsafe.Pointer(u)) = value
}

func (u ActionU) ConfigChange() ActionConfigChange {
	return *(*ActionConfigChange)(unsafe.Pointer(&u))
}

func (u *ActionU) SetOpenURL(value ActionOpenURL) {
	*(*ActionOpenURL)(unsafe.Pointer(u)) = value
}

func (u ActionU) OpenURL() ActionOpenURL {
	return *(*ActionOpenURL)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCloseTabMode(value ActionCloseTabMode) {
	*(*ActionCloseTabMode)(unsafe.Pointer(u)) = value
}

func (u ActionU) CloseTabMode() ActionCloseTabMode {
	return *(*ActionCloseTabMode)(unsafe.Pointer(&u))
}

func (u *ActionU) SetChildExited(value SurfaceMessageChildexited) {
	*(*SurfaceMessageChildexited)(unsafe.Pointer(u)) = value
}

func (u ActionU) ChildExited() SurfaceMessageChildexited {
	return *(*SurfaceMessageChildexited)(unsafe.Pointer(&u))
}

func (u *ActionU) SetProgressReport(value ActionProgressReport) {
	*(*ActionProgressReport)(unsafe.Pointer(u)) = value
}

func (u ActionU) ProgressReport() ActionProgressReport {
	return *(*ActionProgressReport)(unsafe.Pointer(&u))
}

func (u *ActionU) SetCommandFinished(value ActionCommandFinished) {
	*(*ActionCommandFinished)(unsafe.Pointer(u)) = value
}

func (u ActionU) CommandFinished() ActionCommandFinished {
	return *(*ActionCommandFinished)(unsafe.Pointer(&u))
}

func (u *ActionU) SetStartSearch(value ActionStartSearch) {
	*(*ActionStartSearch)(unsafe.Pointer(u)) = value
}

func (u ActionU) StartSearch() ActionStartSearch {
	return *(*ActionStartSearch)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSearchTotal(value ActionSearchTotal) {
	*(*ActionSearchTotal)(unsafe.Pointer(u)) = value
}

func (u ActionU) SearchTotal() ActionSearchTotal {
	return *(*ActionSearchTotal)(unsafe.Pointer(&u))
}

func (u *ActionU) SetSearchSelected(value ActionSearchSelected) {
	*(*ActionSearchSelected)(unsafe.Pointer(u)) = value
}

func (u ActionU) SearchSelected() ActionSearchSelected {
	return *(*ActionSearchSelected)(unsafe.Pointer(&u))
}

func (u *ActionU) SetReadonly(value ActionReadonly) {
	*(*ActionReadonly)(unsafe.Pointer(u)) = value
}

func (u ActionU) Readonly() ActionReadonly {
	return *(*ActionReadonly)(unsafe.Pointer(&u))
}

type AppHandle uintptr

type BindingFlags int32

type BuildMode int32

type ClipboardContent struct {
	Mime *byte
	Data *byte
}

type Clipboard int32

type ClipboardRequest int32

type ColorScheme int32

type ConfigHandle uintptr

type Diagnostic struct {
	Message *byte
}

type EnvVar struct {
	Key   *byte
	Value *byte
}

type Info struct {
	BuildMode  BuildMode
	_          [4]byte
	Version    *byte
	VersionLen uintptr
}

type InputAction int32

type InputKey int32

type InputKeyS struct {
	Action             InputAction
	Mods               InputMods
	ConsumedMods       InputMods
	Keycode            uint32
	Text               *byte
	UnshiftedCodepoint uint32
	Composing          bool
	_                  [3]byte
}

type InputMods int32

type InputMouseButton int32

type InputMouseState int32

type InputScrollMods int32

type InputTriggerKey struct {
	_ [0]uint32
	_ [4]byte
}

func (u *InputTriggerKey) SetPhysical(value InputKey) {
	*(*InputKey)(unsafe.Pointer(u)) = value
}

func (u InputTriggerKey) Physical() InputKey {
	return *(*InputKey)(unsafe.Pointer(&u))
}

func (u *InputTriggerKey) SetUnicode(value uint32) {
	*(*uint32)(unsafe.Pointer(u)) = value
}

func (u InputTriggerKey) Unicode() uint32 {
	return *(*uint32)(unsafe.Pointer(&u))
}

type InputTrigger struct {
	Tag  InputTriggerTag
	Key  InputTriggerKey
	Mods InputMods
}

type InputTriggerTag int32

type InspectorHandle uintptr

type IPCActionNewWindow struct {
	Arguments **byte
}

type IPCAction struct {
	_ [0]uint64
	_ [8]byte
}

func (u *IPCAction) SetNewWindow(value IPCActionNewWindow) {
	*(*IPCActionNewWindow)(unsafe.Pointer(u)) = value
}

func (u IPCAction) NewWindow() IPCActionNewWindow {
	return *(*IPCActionNewWindow)(unsafe.Pointer(&u))
}

type IPCTarget struct {
	_ [0]uint64
	_ [8]byte
}

func (u *IPCTarget) SetKlass(value *byte) {
	*(**byte)(unsafe.Pointer(u)) = value
}

func (u IPCTarget) Klass() *byte {
	return *(**byte)(unsafe.Pointer(&u))
}

type Platform int32

type PlatformIOS struct {
	Uiview unsafe.Pointer
}

type PlatformMacOS struct {
	Nsview unsafe.Pointer
}

type PlatformU struct {
	_ [0]uint64
	_ [8]byte
}

func (u *PlatformU) SetMacOS(value PlatformMacOS) {
	*(*PlatformMacOS)(unsafe.Pointer(u)) = value
}

func (u PlatformU) MacOS() PlatformMacOS {
	return *(*PlatformMacOS)(unsafe.Pointer(&u))
}

func (u *PlatformU) SetIOS(value PlatformIOS) {
	*(*PlatformIOS)(unsafe.Pointer(u)) = value
}

func (u PlatformU) IOS() PlatformIOS {
	return *(*PlatformIOS)(unsafe.Pointer(&u))
}

type PointCoord int32

type Point struct {
	Tag   PointTag
	Coord PointCoord
	X     uint32
	Y     uint32
}

type PointTag int32

type QuickTerminalSizeValue struct {
	_ [0]uint32
	_ [4]byte
}

func (u *QuickTerminalSizeValue) SetPercentage(value float32) {
	*(*float32)(unsafe.Pointer(u)) = value
}

func (u QuickTerminalSizeValue) Percentage() float32 {
	return *(*float32)(unsafe.Pointer(&u))
}

func (u *QuickTerminalSizeValue) SetPixels(value uint32) {
	*(*uint32)(unsafe.Pointer(u)) = value
}

func (u QuickTerminalSizeValue) Pixels() uint32 {
	return *(*uint32)(unsafe.Pointer(&u))
}

type RuntimeActionCb uintptr

type RuntimeCloseSurfaceCb uintptr

type RuntimeConfig struct {
	Userdata                   unsafe.Pointer
	SupportsSelectionClipboard bool
	_                          [7]byte
	WakeupCb                   uintptr
	ActionCb                   uintptr
	ReadClipboardCb            uintptr
	ConfirmReadClipboardCb     uintptr
	WriteClipboardCb           uintptr
	CloseSurfaceCb             uintptr
}

type RuntimeConfirmReadClipboardCb uintptr

type RuntimeReadClipboardCb uintptr

type RuntimeWakeupCb uintptr

type RuntimeWriteClipboardCb uintptr

type Selection struct {
	TopLeft     Point
	BottomRight Point
	Rectangle   bool
	_           [3]byte
}

type String struct {
	Ptr      *byte
	Len      uintptr
	Sentinel bool
	_        [7]byte
}

type SurfaceConfig struct {
	PlatformTag      Platform
	_                [4]byte
	Platform         PlatformU
	Userdata         unsafe.Pointer
	ScaleFactor      float64
	FontSize         float32
	_                [4]byte
	WorkingDirectory *byte
	Command          *byte
	EnvVars          *EnvVar
	EnvVarCount      uintptr
	InitialInput     *byte
	WaitAfterCommand bool
	_                [3]byte
	Context          SurfaceContext
}

type SurfaceContext int32

type SurfaceMessageChildexited struct {
	ExitCode   uint32
	_          [4]byte
	TimetimeMs uint64
}

type SurfaceSize struct {
	Columns      uint16
	Rows         uint16
	WidthPx      uint32
	HeightPx     uint32
	CellWidthPx  uint32
	CellHeightPx uint32
}

type SurfaceHandle uintptr

type Target struct {
	Tag    TargetTag
	_      [4]byte
	Target TargetU
}

type TargetTag int32

type TargetU struct {
	_ [0]uint64
	_ [8]byte
}

func (u *TargetU) SetSurface(value SurfaceHandle) {
	*(*SurfaceHandle)(unsafe.Pointer(u)) = value
}

func (u TargetU) Surface() SurfaceHandle {
	return *(*SurfaceHandle)(unsafe.Pointer(&u))
}

type Text struct {
	TlPxX       float64
	TlPxY       float64
	OffsetStart uint32
	OffsetLen   uint32
	Text        *byte
	TextLen     uintptr
}
